export const seedCategories = [
  {
    name: 'Floor Tiles',
    nameTh: 'กระเบื้องปูพื้น',
    slug: 'floor-tiles',
    description: 'Durable, high-load capacity floor tiles designed for contemporary indoor and exterior architectural spaces.',
    descriptionTh: 'กระเบื้องปูพื้นความแข็งแกร่งสูง รองรับน้ำหนักได้ดี สำหรับพื้นที่พักอาศัยและสถาปัตยกรรมระดับไฮเอนด์',
    image: '/images/rooms/living room.png',
    sortOrder: 1,
    isActive: true,
  },
  {
    name: 'Wall Tiles',
    nameTh: 'กระเบื้องบุผนัง',
    slug: 'wall-tiles',
    description: 'Refined decorative wall surfaces featuring sculpted relief textures, satin finishes, and architectural stone patterns.',
    descriptionTh: 'กระเบื้องบุผนังตกแต่งพื้นผิวระดับพรีเมียม เพิ่มมิติและความหรูหราให้พื้นที่สถาปัตยกรรม',
    image: '/images/rooms/bed room.png',
    sortOrder: 2,
    isActive: true,
  },
  {
    name: 'Bathroom Tiles',
    nameTh: 'กระเบื้องห้องน้ำ',
    slug: 'bathroom-tiles',
    description: 'Water-resistant, non-slip porcelain tiles crafted for modern luxury spa-inspired bathroom sanctuaries.',
    descriptionTh: 'กระเบื้องห้องน้ำกันลื่น ทนความชื้น ดีไซน์สไตล์สปารีสอร์ทระดับหรู',
    image: '/images/rooms/bath room.png',
    sortOrder: 3,
    isActive: true,
  },
  {
    name: 'Outdoor Tiles',
    nameTh: 'กระเบื้องภายนอกและสวน',
    slug: 'outdoor-tiles',
    description: '20mm extra-thick porcelain pavers built for terraces, pool surrounds, and heavy outdoor elements.',
    descriptionTh: 'กระเบื้องภายนอกหนาพิเศษ 20มม. ทนทานต่อแดด ฝน และพื้นที่ลานกิจกรรม',
    image: '/images/rooms/poolside.png',
    sortOrder: 4,
    isActive: true,
  },
  {
    name: 'Wood-look Tiles',
    nameTh: 'กระเบื้องลายไม้',
    slug: 'wood-look-tiles',
    description: 'Authentic timber texture with zero maintenance, combining organic warmth with indestructible ceramic performance.',
    descriptionTh: 'กระเบื้องลายไม้ธรรมชาติเสมือนไม้จริง ทนทาน ไม่บวมน้ำ ดูแลรักษาง่าย',
    image: '/images/rooms/bed room.png',
    sortOrder: 5,
    isActive: true,
  },
];

export const seedBrands = [
  {
    name: 'SUNMA Atelier',
    slug: 'sunma-atelier',
    description: 'In-house signature collection engineered specifically for luxury private residences.',
    country: 'Thailand / Italy',
    logo: '/images/brands/sunma.png',
    isActive: true,
  },
  {
    name: 'Marmi d\'Italia',
    slug: 'marmi-d-italia',
    description: 'Direct imported Italian extra-large slab porcelain tiles reproducing fine Carrara and Calacatta marble.',
    country: 'Italy',
    logo: '/images/brands/marmi.png',
    isActive: true,
  },
  {
    name: 'Kurokin Surface',
    slug: 'kurokin-surface',
    description: 'Japanese minimal dark stone ceramics featuring tactile micro-textured matte finishes.',
    country: 'Japan',
    logo: '/images/brands/kurokin.png',
    isActive: true,
  },
  {
    name: 'Iberica Ceramica',
    slug: 'iberica-ceramica',
    description: 'Spanish artisan ceramic tiles renowned for warm terracotta and rustic glazed accents.',
    country: 'Spain',
    logo: '/images/brands/iberica.png',
    isActive: true,
  },
];

export const seedCollections = [
  {
    name: 'Calacatta Imperiale Series',
    slug: 'calacatta-imperiale',
    description: 'Timeless white marble veining with subtle warm gold threads.',
    isActive: true,
  },
  {
    name: 'Basaltic Minimal Slab',
    slug: 'basaltic-minimal',
    description: 'Deep stone brown and basalt gray porcelain slabs.',
    isActive: true,
  },
  {
    name: 'Nordic Oak Timber Slat',
    slug: 'nordic-oak',
    description: 'Linear natural oak timber grain tiles.',
    isActive: true,
  },
  {
    name: 'Terrazzo Artisanal',
    slug: 'terrazzo-artisanal',
    description: 'Architectural composite stone with quartz chips.',
    isActive: true,
  },
];

export const seedProducts = [
  {
    productCode: 'SNM-FL-001',
    name: 'Calacatta Oro Polished Slab',
    nameTh: 'กระเบื้องลายหินอ่อน Calacatta Oro ผิวเงา',
    slug: 'calacatta-oro-polished-slab',
    categorySlug: 'floor-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'calacatta-imperiale',
    description: 'High-definition Italian porcelain slab featuring dramatic golden-amber veining over a pristine alabaster background. Perfect for grand living rooms and hotel lobbies.',
    descriptionTh: 'กระเบื้องแผ่นใหญ่ลายหินอ่อน Calacatta Oro นำเข้าจากอิตาลี ลวดลายเส้นทองหรูหรา ผิวเงารัศมีสูง เหมาะสำหรับห้องรับแขกและโถงอาคารพรีเมียม',
    shortDescription: '60x120cm Italian polished porcelain slab with gold veining.',
    shortDescriptionTh: 'กระเบื้องแผ่นใหญ่ 60x120ซม. ผิวเงาลายหินอ่อนขาวทอง',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Polished',
    color: 'White & Gold',
    pattern: 'Marble',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 32.5,
    pricePerPiece: 850,
    pricePerBox: 1700,
    stockPieces: 320,
    featured: true,
    thumbnail: '/images/tiles/calacatta-marble.jpeg',
    images: [
      '/images/tiles/calacatta-marble.jpeg',
    ],
  },
  {
    productCode: 'SNM-FL-002',
    name: 'Nero Marquina Charcoal Stone',
    nameTh: 'กระเบื้องหินสีดำ Nero Marquina Charcoal',
    slug: 'nero-marquina-satin-porcelain',
    categorySlug: 'floor-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'basaltic-minimal',
    description: 'Deep rich charcoal black porcelain with micro-etched tactile stone surface providing smooth foot feel without glare.',
    descriptionTh: 'กระเบื้องพอร์ซเลนสีดำชาโคล ผิวสัมผัสหินธรรมชาติ ไม่สะท้อนแสงจัด เหมาะสำหรับพื้นที่ดีไซน์โมเดิร์นลักชัวรี',
    shortDescription: '60x60cm Satin black stone design tile.',
    shortDescriptionTh: 'กระเบื้อง 60x60ซม. สีดำชาโคล ผิวสัมผัสหินซาติน',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Satin',
    color: 'Black',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 30.0,
    pricePerPiece: 420,
    pricePerBox: 1680,
    stockPieces: 450,
    featured: true,
    thumbnail: '/images/tiles/charcoal-stone-1.jpeg',
    images: [
      '/images/tiles/charcoal-stone-1.jpeg',
    ],
  },
  {
    productCode: 'SNM-WL-003',
    name: 'Ivory Travertine Porcelain',
    nameTh: 'กระเบื้องหินทราเวอร์ทีนสีไอวอรี่ Ivory Travertine',
    slug: 'travertino-navona-fluted-wall',
    categorySlug: 'wall-tiles',
    brandSlug: 'iberica-ceramica',
    collectionSlug: 'calacatta-imperiale',
    description: 'Warm cream ivory travertine porcelain tile replicating ancient Roman limestone.',
    descriptionTh: 'กระเบื้องพอร์ซเลนโทนสีครีมไอวอรี่ สไตล์หินทราเวอร์ทีนโรมัน มอบความอบอุ่นและหรูหรา',
    shortDescription: '30x60cm Ivory travertine porcelain tile.',
    shortDescriptionTh: 'กระเบื้อง 30x60ซม. สีครีมไอวอรี่ หินทราเวอร์ทีน',
    size: '30x60',
    width: 30,
    height: 60,
    thickness: 12,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Warm Beige',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Spain',
    piecesPerBox: 8,
    coveragePerBox: 1.44,
    weightPerBox: 24.0,
    pricePerPiece: 290,
    pricePerBox: 2320,
    stockPieces: 210,
    featured: true,
    thumbnail: '/images/tiles/ivory-travertine.jpeg',
    images: [
      '/images/tiles/ivory-travertine.jpeg',
    ],
  },
  {
    productCode: 'SNM-WD-004',
    name: 'Greige Limestone Porcelain',
    nameTh: 'กระเบื้องหินไลม์สโตนสีเกรจ Greige Limestone',
    slug: 'nordic-smoked-oak-plank',
    categorySlug: 'wood-look-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'nordic-oak',
    description: 'Organic greige limestone porcelain with smooth tactile texture and subtle earth veining.',
    descriptionTh: 'กระเบื้องหินธรรมชาติโทนสีเกรจ (เทาอมเบจ) สัมผัสนุ่มนวล ให้ความรู้สึกเป็นธรรมชาติสูง',
    shortDescription: '60x60cm Greige limestone porcelain.',
    shortDescriptionTh: 'กระเบื้อง 60x60ซม. หินไลม์สโตนโทนเกรจ',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Greige',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor/Outdoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 26.5,
    pricePerPiece: 360,
    pricePerBox: 1440,
    stockPieces: 600,
    featured: true,
    thumbnail: '/images/tiles/greige-limestone-1.jpeg',
    images: [
      '/images/tiles/greige-limestone-1.jpeg',
    ],
  },
  {
    productCode: 'SNM-OD-005',
    name: 'Kurokin Dark Charcoal Paver',
    nameTh: 'กระเบื้องลาน Kurokin Dark Charcoal 20มม.',
    slug: 'kurokin-basaltic-paver-20mm',
    categorySlug: 'outdoor-tiles',
    brandSlug: 'kurokin-surface',
    collectionSlug: 'basaltic-minimal',
    description: 'Heavy-duty structural dark basaltic porcelain paver for outdoor terraces and pool decks.',
    descriptionTh: 'กระเบื้องปูลานภายนอกและขอบสระว่ายน้ำสีดำชาโคล รองรับแรงกดทับสูง และทนต่อสภาพอากาศ',
    shortDescription: '60x60cm Dark charcoal outdoor porcelain paver.',
    shortDescriptionTh: 'กระเบื้องปูพื้นภายนอก 60x60ซม. โทนดำชาโคล',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 20,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Dark Gray',
    pattern: 'Concrete',
    indoorOutdoor: 'Outdoor',
    countryOfOrigin: 'Japan',
    piecesPerBox: 2,
    coveragePerBox: 0.72,
    weightPerBox: 33.0,
    pricePerPiece: 680,
    pricePerBox: 1360,
    stockPieces: 180,
    featured: true,
    thumbnail: '/images/tiles/charcoal-stone-2.jpeg',
    images: [
      '/images/tiles/charcoal-stone-2.jpeg',
    ],
  },
  {
    productCode: 'SNM-BT-006',
    name: 'Greige Limestone Soft Satin',
    nameTh: 'กระเบื้องหิน Greige Limestone ผิวซอฟต์ซาติน',
    slug: 'pietra-di-luna-soft-honed',
    categorySlug: 'bathroom-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'basaltic-minimal',
    description: 'Silky smooth stone-textured greige tile designed specifically for moisture-prone wet zones and shower enclosures.',
    descriptionTh: 'กระเบื้องหินธรรมชาติสีเกรจ ผิวสัมผัสนุ่มเท้า สำหรับห้องน้ำและโซนเปียกโดยเฉพาะ',
    shortDescription: '60x60cm Soft honed greige porcelain.',
    shortDescriptionTh: 'กระเบื้องห้องน้ำ 60x60ซม. สีเกรจ นุ่มเท้า',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Satin',
    color: 'Warm Gray',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 29.0,
    pricePerPiece: 390,
    pricePerBox: 1560,
    stockPieces: 400,
    featured: false,
    thumbnail: '/images/tiles/greige-limestone-2.jpeg',
    images: [
      '/images/tiles/greige-limestone-2.jpeg',
    ],
  },
  {
    productCode: 'SNM-FL-007',
    name: 'Italian Artisanal Terrazzo',
    nameTh: 'กระเบื้องเทอร์ราซโซอิตาลี Italian Artisanal',
    slug: 'veneto-terrazzo-micro-charcoal',
    categorySlug: 'floor-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'terrazzo-artisanal',
    description: 'Contemporary Italian terrazzo featuring fine marble quartz chips embedded in a warm neutral base matrix.',
    descriptionTh: 'กระเบื้องลายหินขัดเทอร์ราซโซสไตล์อิตาลี ชิปควอตซ์ธรรมชาติระยิบระยับสวยงาม',
    shortDescription: '60x60cm Fine Italian terrazzo porcelain.',
    shortDescriptionTh: 'กระเบื้องลายหินขัด 60x60ซม. สไตล์อิตาลี',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Beige & White',
    pattern: 'Terrazzo',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 31.0,
    pricePerPiece: 450,
    pricePerBox: 1800,
    stockPieces: 290,
    featured: false,
    thumbnail: '/images/tiles/italian-terrazzo.jpeg',
    images: [
      '/images/tiles/italian-terrazzo.jpeg',
    ],
  },
  {
    productCode: 'SNM-WD-008',
    name: 'Sandstone Beige Porcelain Slab',
    nameTh: 'กระเบื้องหินทรายสีเบจ Sandstone Beige',
    slug: 'walnut-heritage-chevron-slab',
    categorySlug: 'wood-look-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'nordic-oak',
    description: 'Natural sandstone beige texture for prestigious dining suites and executive lounges.',
    descriptionTh: 'กระเบื้องพอร์ซเลนลายหินทรายธรรมชาติสีเบจ เพิ่มความภูมิฐานและหรูหรา',
    shortDescription: '60x120cm Sandstone beige porcelain slab.',
    shortDescriptionTh: 'กระเบื้องแผ่นใหญ่ 60x120ซม. สีเบจหินทราย',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Sandstone Beige',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 32.0,
    pricePerPiece: 920,
    pricePerBox: 1840,
    stockPieces: 150,
    featured: true,
    thumbnail: '/images/tiles/sandstone-beige.jpeg',
    images: [
      '/images/tiles/sandstone-beige.jpeg',
    ],
  },
  {
    productCode: 'SNM-WL-009',
    name: 'Emerald Green Jade Stone',
    nameTh: 'กระเบื้องหินสีเขียวมรกต Emerald Green Jade',
    slug: 'zellige-emerald-green-glazed',
    categorySlug: 'wall-tiles',
    brandSlug: 'iberica-ceramica',
    collectionSlug: 'terrazzo-artisanal',
    description: 'Jewel-toned deep emerald green jade stone porcelain tile.',
    descriptionTh: 'กระเบื้องพอร์ซเลนลายหินสีเขียวมรกต เฉดสีหยกธรรมชาติ ลวดลายทรงคุณค่า',
    shortDescription: '30x60cm Emerald green stone tile.',
    shortDescriptionTh: 'กระเบื้องหินธรรมชาติ 30x60ซม. สีเขียวมรกต',
    size: '30x60',
    width: 30,
    height: 60,
    thickness: 9,
    material: 'Porcelain',
    surface: 'Polished',
    color: 'Emerald Green',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Spain',
    piecesPerBox: 8,
    coveragePerBox: 1.44,
    weightPerBox: 22.0,
    pricePerPiece: 310,
    pricePerBox: 2480,
    stockPieces: 310,
    featured: false,
    thumbnail: '/images/tiles/green-stone.jpeg',
    images: [
      '/images/tiles/green-stone.jpeg',
    ],
  },
  {
    productCode: 'SNM-BT-010',
    name: 'Silver Mist Marble Porcelain',
    nameTh: 'กระเบื้องหินอ่อนสีเทาเงิน Silver Mist Marble',
    slug: 'grigio-carnico-polished-porcelain',
    categorySlug: 'bathroom-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'calacatta-imperiale',
    description: 'Exclusive silver mist marble tile with vibrant white veining for sanctuary bathroom walls and floors.',
    descriptionTh: 'กระเบื้องหินอ่อนอิตาลีโทนสีเทาเงินตัดเส้นขาว มอบบรรยากาศห้องน้ำและห้องรับแขกระดับ 5 ดาว',
    shortDescription: '60x120cm Polished silver mist marble porcelain.',
    shortDescriptionTh: 'กระเบื้อง 60x120ซม. ผิวเงาลายหินอ่อนเทาเงิน',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Polished',
    color: 'Silver Gray',
    pattern: 'Marble',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 33.0,
    pricePerPiece: 890,
    pricePerBox: 1780,
    stockPieces: 260,
    featured: true,
    thumbnail: '/images/tiles/silver-mist-marble.jpeg',
    images: [
      '/images/tiles/silver-mist-marble.jpeg',
    ],
  },
];

export const seedRooms = [
  {
    name: 'Modern Architectural Living Room',
    nameTh: 'ห้องรับแขกสถาปัตยกรรมร่วมสมัย',
    slug: 'living-room',
    imageUrl: '/images/rooms/living room.png',
    description: 'Spacious high-ceiling lounge with floor-to-ceiling glass and panoramic garden view.',
    areas: [
      {
        name: 'Main Floor Area',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,530 420,480 930,480 1100,460 1000,530 1480,630 1600,630 1600,900 0,900',
        defaultTileAspectRatio: '1:1',
      },
    ],
  },
  {
    name: 'Luxury Sanctuary Bathroom',
    nameTh: 'ห้องน้ำดีไซน์รีสอร์ทระดับหรู',
    slug: 'bathroom',
    imageUrl: '/images/rooms/bath room.png',
    description: 'Minimal spa bathroom with freestanding tub and floating quartz vanity.',
    areas: [
      {
        name: 'Bathroom Floor',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,660 120,620 360,550 360,500 650,490 1090,480 1600,560 1600,900 0,900',
        defaultTileAspectRatio: '1:1',
      },
    ],
  },
  {
    name: 'Master Architectural Bedroom',
    nameTh: 'ห้องนอนมาสเตอร์สวีท',
    slug: 'bedroom',
    imageUrl: '/images/rooms/bed room.png',
    description: 'Serene master bedroom suite with warm lighting and ambient acoustic finishes.',
    areas: [
      {
        name: 'Bedroom Suite Floor',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,530 200,490 760,475 850,460 720,520 1060,650 1380,550 1600,620 1600,900 0,900',
        defaultTileAspectRatio: '1:1',
      },
    ],
  },
  {
    name: 'Chef Kitchen & Dining Space',
    nameTh: 'ห้องครัวและโซนรับประทานอาหาร',
    slug: 'kitchen',
    imageUrl: '/images/rooms/kitchen room.png',
    description: 'Professional chef kitchen with dark marble waterfall island and brass fixtures.',
    areas: [
      {
        name: 'Kitchen & Island Floor',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,690 240,500 840,460 1600,580 1600,900 0,900',
        defaultTileAspectRatio: '1:2',
      },
    ],
  },
  {
    name: 'Outdoor Terrace & Pool Deck',
    nameTh: 'ลานระเบียงและสระว่ายน้ำภายนอก',
    slug: 'outdoor',
    imageUrl: '/images/rooms/poolside.png',
    description: 'Sunlit alfresco dining terrace overlooking infinity swimming pool.',
    areas: [
      {
        name: 'Terrace Floor Paver',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,900 0,720 680,430 1030,400 1600,500 1600,900 0,900',
        defaultTileAspectRatio: '1:1',
      },
    ],
  },
];

export const seedPromotions = [
  {
    name: 'Grand Architectural Launch - 15% OFF Italian Slabs',
    discountPercentage: '15.00',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    isActive: true,
    minQuantity: 2,
  },
];
