export const seedCategories = [
  {
    name: 'Floor Tiles',
    nameTh: 'กระเบื้องปูพื้น',
    slug: 'floor-tiles',
    description: 'Durable, high-load capacity floor tiles designed for contemporary indoor and exterior architectural spaces.',
    descriptionTh: 'กระเบื้องปูพื้นความแข็งแกร่งสูง รองรับน้ำหนักได้ดี สำหรับพื้นที่พักอาศัยและสถาปัตยกรรมระดับไฮเอนด์',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 1,
    isActive: true,
  },
  {
    name: 'Wall Tiles',
    nameTh: 'กระเบื้องบุผนัง',
    slug: 'wall-tiles',
    description: 'Refined decorative wall surfaces featuring sculpted relief textures, satin finishes, and architectural stone patterns.',
    descriptionTh: 'กระเบื้องบุผนังตกแต่งพื้นผิวระดับพรีเมียม เพิ่มมิติและความหรูหราให้พื้นที่สถาปัตยกรรม',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 2,
    isActive: true,
  },
  {
    name: 'Bathroom Tiles',
    nameTh: 'กระเบื้องห้องน้ำ',
    slug: 'bathroom-tiles',
    description: 'Water-resistant, non-slip porcelain tiles crafted for modern luxury spa-inspired bathroom sanctuaries.',
    descriptionTh: 'กระเบื้องห้องน้ำกันลื่น ทนความชื้น ดีไซน์สไตล์สปารีสอร์ทระดับหรู',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 3,
    isActive: true,
  },
  {
    name: 'Outdoor Tiles',
    nameTh: 'กระเบื้องภายนอกและสวน',
    slug: 'outdoor-tiles',
    description: '20mm extra-thick porcelain pavers built for terraces, pool surrounds, and heavy outdoor elements.',
    descriptionTh: 'กระเบื้องภายนอกหนาพิเศษ 20มม. ทนทานต่อแดด ฝน และพื้นที่ลานกิจกรรม',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 4,
    isActive: true,
  },
  {
    name: 'Wood-look Tiles',
    nameTh: 'กระเบื้องลายไม้',
    slug: 'wood-look-tiles',
    description: 'Authentic timber texture with zero maintenance, combining organic warmth with indestructible ceramic performance.',
    descriptionTh: 'กระเบื้องลายไม้ธรรมชาติเสมือนไม้จริง ทนทาน ไม่บวมน้ำ ดูแลรักษาง่าย',
    image: 'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 5,
    isActive: true,
  },
];

export const seedBrands = [
  {
    name: 'SUNMA Atelier',
    slug: 'sunma-atelier',
    description: 'In-house signature collection engineered specifically for luxury private residences.',
    country: 'Thailand / Italy',
    logo: '/images/brands/sunma.png',
    isActive: true,
  },
  {
    name: 'Marmi d\'Italia',
    slug: 'marmi-d-italia',
    description: 'Direct imported Italian extra-large slab porcelain tiles reproducing fine Carrara and Calacatta marble.',
    country: 'Italy',
    logo: '/images/brands/marmi.png',
    isActive: true,
  },
  {
    name: 'Kurokin Surface',
    slug: 'kurokin-surface',
    description: 'Japanese minimal dark stone ceramics featuring tactile micro-textured matte finishes.',
    country: 'Japan',
    logo: '/images/brands/kurokin.png',
    isActive: true,
  },
  {
    name: 'Iberica Ceramica',
    slug: 'iberica-ceramica',
    description: 'Spanish artisan ceramic tiles renowned for warm terracotta and rustic glazed accents.',
    country: 'Spain',
    logo: '/images/brands/iberica.png',
    isActive: true,
  },
];

export const seedCollections = [
  {
    name: 'Calacatta Imperiale Series',
    slug: 'calacatta-imperiale',
    description: 'Timeless white marble veining with subtle warm gold threads.',
    isActive: true,
  },
  {
    name: 'Basaltic Minimal Slab',
    slug: 'basaltic-minimal',
    description: 'Deep stone brown and basalt gray porcelain slabs.',
    isActive: true,
  },
  {
    name: 'Nordic Oak Timber Slat',
    slug: 'nordic-oak',
    description: 'Linear natural oak timber grain tiles.',
    isActive: true,
  },
  {
    name: 'Terrazzo Artisanal',
    slug: 'terrazzo-artisanal',
    description: 'Architectural composite stone with quartz chips.',
    isActive: true,
  },
];

export const seedProducts = [
  {
    productCode: 'SNM-FL-001',
    name: 'Calacatta Oro Polished Slab',
    nameTh: 'กระเบื้องลายหินอ่อน Calacatta Oro ผิวเงา',
    slug: 'calacatta-oro-polished-slab',
    categorySlug: 'floor-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'calacatta-imperiale',
    description: 'High-definition Italian porcelain slab featuring dramatic golden-amber veining over a pristine alabaster background. Perfect for grand living rooms and hotel lobbies.',
    descriptionTh: 'กระเบื้องแผ่นใหญ่ลายหินอ่อน Calacatta Oro นำเข้าจากอิตาลี ลวดลายเส้นทองหรูหรา ผิวเงารัศมีสูง เหมาะสำหรับห้องรับแขกและโถงอาคารพรีเมียม',
    shortDescription: '60x120cm Italian polished porcelain slab with gold veining.',
    shortDescriptionTh: 'กระเบื้องแผ่นใหญ่ 60x120ซม. ผิวเงาลายหินอ่อนขาวทอง',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Polished',
    color: 'White & Gold',
    pattern: 'Marble',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 32.5,
    pricePerPiece: 850,
    pricePerBox: 1700,
    stockPieces: 320,
    featured: true,
    thumbnail: '/images/tiles/calacatta-marble.jpeg',
    images: [
      '/images/tiles/calacatta-marble.jpeg',
    ],
  },
  {
    productCode: 'SNM-FL-002',
    name: 'Nero Marquina Charcoal Stone',
    nameTh: 'กระเบื้องหินสีดำ Nero Marquina Charcoal',
    slug: 'nero-marquina-satin-porcelain',
    categorySlug: 'floor-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'basaltic-minimal',
    description: 'Deep rich charcoal black porcelain with micro-etched tactile stone surface providing smooth foot feel without glare.',
    descriptionTh: 'กระเบื้องพอร์ซเลนสีดำชาโคล ผิวสัมผัสหินธรรมชาติ ไม่สะท้อนแสงจัด เหมาะสำหรับพื้นที่ดีไซน์โมเดิร์นลักชัวรี',
    shortDescription: '60x60cm Satin black stone design tile.',
    shortDescriptionTh: 'กระเบื้อง 60x60ซม. สีดำชาโคล ผิวสัมผัสหินซาติน',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Satin',
    color: 'Black',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 30.0,
    pricePerPiece: 420,
    pricePerBox: 1680,
    stockPieces: 450,
    featured: true,
    thumbnail: '/images/tiles/charcoal-stone-1.jpeg',
    images: [
      '/images/tiles/charcoal-stone-1.jpeg',
    ],
  },
  {
    productCode: 'SNM-WL-003',
    name: 'Ivory Travertine Porcelain',
    nameTh: 'กระเบื้องหินทราเวอร์ทีนสีไอวอรี่ Ivory Travertine',
    slug: 'travertino-navona-fluted-wall',
    categorySlug: 'wall-tiles',
    brandSlug: 'iberica-ceramica',
    collectionSlug: 'calacatta-imperiale',
    description: 'Warm cream ivory travertine porcelain tile replicating ancient Roman limestone.',
    descriptionTh: 'กระเบื้องพอร์ซเลนโทนสีครีมไอวอรี่ สไตล์หินทราเวอร์ทีนโรมัน มอบความอบอุ่นและหรูหรา',
    shortDescription: '30x60cm Ivory travertine porcelain tile.',
    shortDescriptionTh: 'กระเบื้อง 30x60ซม. สีครีมไอวอรี่ หินทราเวอร์ทีน',
    size: '30x60',
    width: 30,
    height: 60,
    thickness: 12,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Warm Beige',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Spain',
    piecesPerBox: 8,
    coveragePerBox: 1.44,
    weightPerBox: 24.0,
    pricePerPiece: 290,
    pricePerBox: 2320,
    stockPieces: 210,
    featured: true,
    thumbnail: '/images/tiles/ivory-travertine.jpeg',
    images: [
      '/images/tiles/ivory-travertine.jpeg',
    ],
  },
  {
    productCode: 'SNM-WD-004',
    name: 'Greige Limestone Porcelain',
    nameTh: 'กระเบื้องหินไลม์สโตนสีเกรจ Greige Limestone',
    slug: 'nordic-smoked-oak-plank',
    categorySlug: 'wood-look-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'nordic-oak',
    description: 'Organic greige limestone porcelain with smooth tactile texture and subtle earth veining.',
    descriptionTh: 'กระเบื้องหินธรรมชาติโทนสีเกรจ (เทาอมเบจ) สัมผัสนุ่มนวล ให้ความรู้สึกเป็นธรรมชาติสูง',
    shortDescription: '60x60cm Greige limestone porcelain.',
    shortDescriptionTh: 'กระเบื้อง 60x60ซม. หินไลม์สโตนโทนเกรจ',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Greige',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor/Outdoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 26.5,
    pricePerPiece: 360,
    pricePerBox: 1440,
    stockPieces: 600,
    featured: true,
    thumbnail: '/images/tiles/greige-limestone-1.jpeg',
    images: [
      '/images/tiles/greige-limestone-1.jpeg',
    ],
  },
  {
    productCode: 'SNM-OD-005',
    name: 'Kurokin Dark Charcoal Paver',
    nameTh: 'กระเบื้องลาน Kurokin Dark Charcoal 20มม.',
    slug: 'kurokin-basaltic-paver-20mm',
    categorySlug: 'outdoor-tiles',
    brandSlug: 'kurokin-surface',
    collectionSlug: 'basaltic-minimal',
    description: 'Heavy-duty structural dark basaltic porcelain paver for outdoor terraces and pool decks.',
    descriptionTh: 'กระเบื้องปูลานภายนอกและขอบสระว่ายน้ำสีดำชาโคล รองรับแรงกดทับสูง และทนต่อสภาพอากาศ',
    shortDescription: '60x60cm Dark charcoal outdoor porcelain paver.',
    shortDescriptionTh: 'กระเบื้องปูพื้นภายนอก 60x60ซม. โทนดำชาโคล',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 20,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Dark Gray',
    pattern: 'Concrete',
    indoorOutdoor: 'Outdoor',
    countryOfOrigin: 'Japan',
    piecesPerBox: 2,
    coveragePerBox: 0.72,
    weightPerBox: 33.0,
    pricePerPiece: 680,
    pricePerBox: 1360,
    stockPieces: 180,
    featured: true,
    thumbnail: '/images/tiles/charcoal-stone-2.jpeg',
    images: [
      '/images/tiles/charcoal-stone-2.jpeg',
    ],
  },
  {
    productCode: 'SNM-BT-006',
    name: 'Greige Limestone Soft Satin',
    nameTh: 'กระเบื้องหิน Greige Limestone ผิวซอฟต์ซาติน',
    slug: 'pietra-di-luna-soft-honed',
    categorySlug: 'bathroom-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'basaltic-minimal',
    description: 'Silky smooth stone-textured greige tile designed specifically for moisture-prone wet zones and shower enclosures.',
    descriptionTh: 'กระเบื้องหินธรรมชาติสีเกรจ ผิวสัมผัสนุ่มเท้า สำหรับห้องน้ำและโซนเปียกโดยเฉพาะ',
    shortDescription: '60x60cm Soft honed greige porcelain.',
    shortDescriptionTh: 'กระเบื้องห้องน้ำ 60x60ซม. สีเกรจ นุ่มเท้า',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Satin',
    color: 'Warm Gray',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 29.0,
    pricePerPiece: 390,
    pricePerBox: 1560,
    stockPieces: 400,
    featured: false,
    thumbnail: '/images/tiles/greige-limestone-2.jpeg',
    images: [
      '/images/tiles/greige-limestone-2.jpeg',
    ],
  },
  {
    productCode: 'SNM-FL-007',
    name: 'Italian Artisanal Terrazzo',
    nameTh: 'กระเบื้องเทอร์ราซโซอิตาลี Italian Artisanal',
    slug: 'veneto-terrazzo-micro-charcoal',
    categorySlug: 'floor-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'terrazzo-artisanal',
    description: 'Contemporary Italian terrazzo featuring fine marble quartz chips embedded in a warm neutral base matrix.',
    descriptionTh: 'กระเบื้องลายหินขัดเทอร์ราซโซสไตล์อิตาลี ชิปควอตซ์ธรรมชาติระยิบระยับสวยงาม',
    shortDescription: '60x60cm Fine Italian terrazzo porcelain.',
    shortDescriptionTh: 'กระเบื้องลายหินขัด 60x60ซม. สไตล์อิตาลี',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Beige & White',
    pattern: 'Terrazzo',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 31.0,
    pricePerPiece: 450,
    pricePerBox: 1800,
    stockPieces: 290,
    featured: false,
    thumbnail: '/images/tiles/italian-terrazzo.jpeg',
    images: [
      '/images/tiles/italian-terrazzo.jpeg',
    ],
  },
  {
    productCode: 'SNM-WD-008',
    name: 'Sandstone Beige Porcelain Slab',
    nameTh: 'กระเบื้องหินทรายสีเบจ Sandstone Beige',
    slug: 'walnut-heritage-chevron-slab',
    categorySlug: 'wood-look-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'nordic-oak',
    description: 'Natural sandstone beige texture for prestigious dining suites and executive lounges.',
    descriptionTh: 'กระเบื้องพอร์ซเลนลายหินทรายธรรมชาติสีเบจ เพิ่มความภูมิฐานและหรูหรา',
    shortDescription: '60x120cm Sandstone beige porcelain slab.',
    shortDescriptionTh: 'กระเบื้องแผ่นใหญ่ 60x120ซม. สีเบจหินทราย',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Sandstone Beige',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 32.0,
    pricePerPiece: 920,
    pricePerBox: 1840,
    stockPieces: 150,
    featured: true,
    thumbnail: '/images/tiles/sandstone-beige.jpeg',
    images: [
      '/images/tiles/sandstone-beige.jpeg',
    ],
  },
  {
    productCode: 'SNM-WL-009',
    name: 'Emerald Green Jade Stone',
    nameTh: 'กระเบื้องหินสีเขียวมรกต Emerald Green Jade',
    slug: 'zellige-emerald-green-glazed',
    categorySlug: 'wall-tiles',
    brandSlug: 'iberica-ceramica',
    collectionSlug: 'terrazzo-artisanal',
    description: 'Jewel-toned deep emerald green jade stone porcelain tile.',
    descriptionTh: 'กระเบื้องพอร์ซเลนลายหินสีเขียวมรกต เฉดสีหยกธรรมชาติ ลวดลายทรงคุณค่า',
    shortDescription: '30x60cm Emerald green stone tile.',
    shortDescriptionTh: 'กระเบื้องหินธรรมชาติ 30x60ซม. สีเขียวมรกต',
    size: '30x60',
    width: 30,
    height: 60,
    thickness: 9,
    material: 'Porcelain',
    surface: 'Polished',
    color: 'Emerald Green',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Spain',
    piecesPerBox: 8,
    coveragePerBox: 1.44,
    weightPerBox: 22.0,
    pricePerPiece: 310,
    pricePerBox: 2480,
    stockPieces: 310,
    featured: false,
    thumbnail: '/images/tiles/green-stone.jpeg',
    images: [
      '/images/tiles/green-stone.jpeg',
    ],
  },
  {
    productCode: 'SNM-BT-010',
    name: 'Silver Mist Marble Porcelain',
    nameTh: 'กระเบื้องหินอ่อนสีเทาเงิน Silver Mist Marble',
    slug: 'grigio-carnico-polished-porcelain',
    categorySlug: 'bathroom-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'calacatta-imperiale',
    description: 'Exclusive silver mist marble tile with vibrant white veining for sanctuary bathroom walls and floors.',
    descriptionTh: 'กระเบื้องหินอ่อนอิตาลีโทนสีเทาเงินตัดเส้นขาว มอบบรรยากาศห้องน้ำและห้องรับแขกระดับ 5 ดาว',
    shortDescription: '60x120cm Polished silver mist marble porcelain.',
    shortDescriptionTh: 'กระเบื้อง 60x120ซม. ผิวเงาลายหินอ่อนเทาเงิน',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Polished',
    color: 'Silver Gray',
    pattern: 'Marble',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 33.0,
    pricePerPiece: 890,
    pricePerBox: 1780,
    stockPieces: 260,
    featured: true,
    thumbnail: '/images/tiles/silver-mist-marble.jpeg',
    images: [
      '/images/tiles/silver-mist-marble.jpeg',
    ],
  },
  {
    productCode: 'SNM-OD-011',
    name: 'Sandstone Beige Pool Coping 20mm',
    nameTh: 'กระเบื้องขอบสระ Sandstone Beige 20มม.',
    slug: 'sandstone-beige-pool-coping-20mm',
    categorySlug: 'outdoor-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'basaltic-minimal',
    description: 'Salt-resistant, thermal-shock proof sandstone look porcelain tile designed for swimming pool surrounds.',
    descriptionTh: 'กระเบื้องสระว่ายน้ำและลานกลางแจ้ง ทนคลอรีนและน้ำเค็ม ผิวสัมผัสหินทรายกันลื่น ไม่สะสมความร้อน',
    shortDescription: '60x60cm 20mm Sandstone textured outdoor tile.',
    shortDescriptionTh: 'กระเบื้องลานสระ 60x60ซม. หนา 20มม. กันลื่นสีเบจ',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 20,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Warm Beige',
    pattern: 'Stone',
    indoorOutdoor: 'Outdoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 2,
    coveragePerBox: 0.72,
    weightPerBox: 32.0,
    pricePerPiece: 640,
    pricePerBox: 1280,
    stockPieces: 340,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-FL-012',
    name: 'Concrete Raw Slate Matt',
    nameTh: 'กระเบื้องลายปูนเปลือย Concrete Raw Slate',
    slug: 'concrete-raw-slate-matt',
    categorySlug: 'floor-tiles',
    brandSlug: 'kurokin-surface',
    collectionSlug: 'basaltic-minimal',
    description: 'Architectural industrial micro-cement effect tile with subtle tactile trowel marks.',
    descriptionTh: 'กระเบื้องลายปูนขัดมันสไตล์ลอฟท์ มอบฟีลลิ่งดิบเท่ เรียบหรู สำหรับคอนโดและสตูดิโอสถาปนิก',
    shortDescription: '60x60cm Raw concrete look matt porcelain.',
    shortDescriptionTh: 'กระเบื้องปูนเปลือย 60x60ซม. ผิวด้านสไตล์ลอฟท์',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Warm Gray',
    pattern: 'Concrete',
    indoorOutdoor: 'Indoor/Outdoor',
    countryOfOrigin: 'Japan',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 28.5,
    pricePerPiece: 380,
    pricePerBox: 1520,
    stockPieces: 520,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-WD-013',
    name: 'Teak Natural Heritage Plank',
    nameTh: 'กระเบื้องลายไม้ Teak Natural Heritage',
    slug: 'teak-natural-heritage-plank',
    categorySlug: 'wood-look-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'nordic-oak',
    description: 'Golden Thai teak wood pattern reproduced on durable porcelain tile planks.',
    descriptionTh: 'กระเบื้องลายไม้สักทองธรรมชาติ ลวดลายอบอุ่น ให้ความรู้สึกผ่อนคลายและสัมผัสใกล้ชิดธรรมชาติ',
    shortDescription: '20x120cm Natural teak wood effect plank.',
    shortDescriptionTh: 'กระเบื้องลายไม้สัก 20x120ซม. โทนสีทองธรรมชาติ',
    size: '20x120',
    width: 20,
    height: 120,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Stone Brown',
    pattern: 'Wood',
    indoorOutdoor: 'Indoor/Outdoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 5,
    coveragePerBox: 1.20,
    weightPerBox: 26.0,
    pricePerPiece: 370,
    pricePerBox: 1850,
    stockPieces: 410,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-WL-014',
    name: 'Statuario Micro Velvet Wall',
    nameTh: 'กระเบื้องบุผนัง Statuario Micro Velvet',
    slug: 'statuario-micro-velvet-wall',
    categorySlug: 'wall-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'calacatta-imperiale',
    description: 'Silky micro-velvet finish on white Statuario marble ceramic tiles for luxury vanity backsplash.',
    descriptionTh: 'กระเบื้องผนัง Statuario ขาวบริสุทธิ์ เส้นแร่เทา ผิวสัมผัสแบบไมโครเวลเวท ละมุนดุจกำมะหยี่',
    shortDescription: '30x60cm Statuario velvet finish wall tile.',
    shortDescriptionTh: 'กระเบื้องผนัง 30x60ซม. ผิวเวลเวทสัมผัสนุ่ม',
    size: '30x60',
    width: 30,
    height: 60,
    thickness: 8.5,
    material: 'Ceramic',
    surface: 'Satin',
    color: 'Off-white',
    pattern: 'Marble',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 8,
    coveragePerBox: 1.44,
    weightPerBox: 21.5,
    pricePerPiece: 280,
    pricePerBox: 2240,
    stockPieces: 380,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-FL-015',
    name: 'Volcanic Lava Black Honed',
    nameTh: 'กระเบื้องหินภูเขาไฟ Volcanic Lava Black',
    slug: 'volcanic-lava-black-honed',
    categorySlug: 'floor-tiles',
    brandSlug: 'kurokin-surface',
    collectionSlug: 'basaltic-minimal',
    description: 'Porous volcanic lava stone texture rendered in durable porcelain slabs.',
    descriptionTh: 'กระเบื้องผิวหินภูเขาไฟสีดำเข้ม มอบความเงียบสงบ ลุ่มลึก สไตล์เรียบสัจจะ Zen Architecture',
    shortDescription: '60x120cm Volcanic basalt porcelain slab.',
    shortDescriptionTh: 'กระเบื้องแผ่นใหญ่ 60x120ซม. ผิวหินภูเขาไฟสีดำ',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Black',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor/Outdoor',
    countryOfOrigin: 'Japan',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 34.0,
    pricePerPiece: 790,
    pricePerBox: 1580,
    stockPieces: 230,
    featured: true,
    thumbnail: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-BT-016',
    name: 'Ceppo di Gre Neutral Slab',
    nameTh: 'กระเบื้อง Ceppo di Gre Neutral',
    slug: 'ceppo-di-gre-neutral-slab',
    categorySlug: 'bathroom-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'terrazzo-artisanal',
    description: 'Iconic Milanese Ceppo di Gre pebble aggregate porcelain tile for modern wet-room floors.',
    descriptionTh: 'กระเบื้องหินกรวด Ceppo di Gre สไตล์มิลานยอดนิยม สำหรับพื้นและผนังห้องน้ำสปาสุดหรู',
    shortDescription: '60x60cm Ceppo di Gre stone texture porcelain.',
    shortDescriptionTh: 'กระเบื้องลายหินกรวดมิลาน 60x60ซม.',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Warm Gray',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 30.5,
    pricePerPiece: 490,
    pricePerBox: 1960,
    stockPieces: 330,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-OD-017',
    name: 'Granite Charcoal Paver 20mm',
    nameTh: 'กระเบื้องแกรนิตภายนอก Charcoal 20มม.',
    slug: 'granite-charcoal-paver-20mm',
    categorySlug: 'outdoor-tiles',
    brandSlug: 'kurokin-surface',
    collectionSlug: 'basaltic-minimal',
    description: 'Flame-finished dark granite effect porcelain paver engineered for outdoor driveways and courtyards.',
    descriptionTh: 'กระเบื้องลายแกรนิตพ่นไฟ 20มม. ทนรอยขีดข่วน คราบน้ำมัน และแรงกดทับของรถยนต์',
    shortDescription: '60x60cm 20mm Flamed granite look paver.',
    shortDescriptionTh: 'กระเบื้องลานจอดรถ 60x60ซม. หนา 20มม.',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 20,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Black',
    pattern: 'Stone',
    indoorOutdoor: 'Outdoor',
    countryOfOrigin: 'Japan',
    piecesPerBox: 2,
    coveragePerBox: 0.72,
    weightPerBox: 33.5,
    pricePerPiece: 710,
    pricePerBox: 1420,
    stockPieces: 190,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-WL-018',
    name: 'Artisan Bronze Metallic Relief',
    nameTh: 'กระเบื้องผนัง Artisan Bronze ลายโลหะ',
    slug: 'artisan-bronze-metallic-relief',
    categorySlug: 'wall-tiles',
    brandSlug: 'iberica-ceramica',
    collectionSlug: 'basaltic-minimal',
    description: 'Subtle metallic shimmering glazed ceramic wall tile designed for high-end bar backdrops and reception desks.',
    descriptionTh: 'กระเบื้องผนังประกายโลหะบรอนซ์ทอง สะท้อนแสงเงาหรูหรา สำหรับผนังเคาน์เตอร์บาร์และแผนกต้อนรับ',
    shortDescription: '30x60cm Shimmering metallic bronze wall tile.',
    shortDescriptionTh: 'กระเบื้องผนัง 30x60ซม. ประกายโลหะบรอนซ์ทอง',
    size: '30x60',
    width: 30,
    height: 60,
    thickness: 9,
    material: 'Ceramic',
    surface: 'Satin',
    color: 'Bronze / Gold',
    pattern: 'Concrete',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Spain',
    piecesPerBox: 8,
    coveragePerBox: 1.44,
    weightPerBox: 23.0,
    pricePerPiece: 340,
    pricePerBox: 2720,
    stockPieces: 270,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-FL-019',
    name: 'Pietra Grey Polished Slab',
    nameTh: 'กระเบื้องลายหินอ่อน Pietra Grey ผิวเงา',
    slug: 'pietra-grey-polished-slab',
    categorySlug: 'floor-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'calacatta-imperiale',
    description: 'Persian Pietra grey polished porcelain with charcoal slate tones and fine linear quartz chalk threads.',
    descriptionTh: 'กระเบื้องพอร์ซเลนแผ่นใหญ่ Pietra Grey สีเทาเข้มลายเส้นแร่ขาว ผิวเงาสระกระจก หรูหราเหนือกาลเวลา',
    shortDescription: '60x120cm Polished Pietra Grey marble porcelain.',
    shortDescriptionTh: 'กระเบื้อง 60x120ซม. ลายหินอ่อนสีเทา Pietra Grey',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Polished',
    color: 'Dark Gray',
    pattern: 'Marble',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 32.8,
    pricePerPiece: 870,
    pricePerBox: 1740,
    stockPieces: 240,
    featured: true,
    thumbnail: 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-WD-020',
    name: 'Ebony Black Wood Plank',
    nameTh: 'กระเบื้องลายไม้ไม้มะเกลือ Ebony Black',
    slug: 'ebony-black-wood-plank',
    categorySlug: 'wood-look-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'nordic-oak',
    description: 'Jet black stained wood-look porcelain planks for sophisticated dark moody interiors and architectural suites.',
    descriptionTh: 'กระเบื้องลายไม้สีดำไม้มะเกลือ ดึงสายตาด้วยความลุ่มลึก เพิ่มเอกลักษณ์ให้พื้นที่ส่วนตัว',
    shortDescription: '20x120cm Black stained timber look porcelain plank.',
    shortDescriptionTh: 'กระเบื้องลายไม้สีดำ 20x120ซม.',
    size: '20x120',
    width: 20,
    height: 120,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Black',
    pattern: 'Wood',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 5,
    coveragePerBox: 1.20,
    weightPerBox: 26.2,
    pricePerPiece: 390,
    pricePerBox: 1950,
    stockPieces: 300,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
    ],
  },
];

export const seedRooms = [
  {
    name: 'Modern Architectural Living Room',
    nameTh: 'ห้องรับแขกสถาปัตยกรรมร่วมสมัย',
    slug: 'living-room',
    imageUrl: '/images/rooms/living room.png',
    description: 'Spacious high-ceiling lounge with floor-to-ceiling glass and panoramic garden view.',
    areas: [
      {
        name: 'Main Floor Area',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,530 420,480 930,480 1100,460 1000,530 1480,630 1600,630 1600,900 0,900',
        defaultTileAspectRatio: '1:1',
      },
    ],
  },
  {
    name: 'Luxury Sanctuary Bathroom',
    nameTh: 'ห้องน้ำดีไซน์รีสอร์ทระดับหรู',
    slug: 'bathroom',
    imageUrl: '/images/rooms/bath room.png',
    description: 'Minimal spa bathroom with freestanding tub and floating quartz vanity.',
    areas: [
      {
        name: 'Bathroom Floor',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,660 120,620 360,550 360,500 650,490 1090,480 1600,560 1600,900 0,900',
        defaultTileAspectRatio: '1:1',
      },
    ],
  },
  {
    name: 'Master Architectural Bedroom',
    nameTh: 'ห้องนอนมาสเตอร์สวีท',
    slug: 'bedroom',
    imageUrl: '/images/rooms/bed room.png',
    description: 'Serene master bedroom suite with warm lighting and ambient acoustic finishes.',
    areas: [
      {
        name: 'Bedroom Suite Floor',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,530 200,490 760,475 850,460 720,520 1060,650 1380,550 1600,620 1600,900 0,900',
        defaultTileAspectRatio: '1:1',
      },
    ],
  },
  {
    name: 'Chef Kitchen & Dining Space',
    nameTh: 'ห้องครัวและโซนรับประทานอาหาร',
    slug: 'kitchen',
    imageUrl: '/images/rooms/kitchen room.png',
    description: 'Professional chef kitchen with dark marble waterfall island and brass fixtures.',
    areas: [
      {
        name: 'Kitchen & Island Floor',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,690 240,500 840,460 1600,580 1600,900 0,900',
        defaultTileAspectRatio: '1:2',
      },
    ],
  },
  {
    name: 'Outdoor Terrace & Pool Deck',
    nameTh: 'ลานระเบียงและสระว่ายน้ำภายนอก',
    slug: 'outdoor',
    imageUrl: '/images/rooms/poolside.png',
    description: 'Sunlit alfresco dining terrace overlooking infinity swimming pool.',
    areas: [
      {
        name: 'Terrace Floor Paver',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,900 0,720 680,430 1030,400 1600,500 1600,900 0,900',
        defaultTileAspectRatio: '1:1',
      },
    ],
  },
];

export const seedPromotions = [
  {
    name: 'Grand Architectural Launch - 15% OFF Italian Slabs',
    discountPercentage: '15.00',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    isActive: true,
    minQuantity: 2,
  },
];
