export const seedCategories = [
  {
    name: 'Floor Tiles',
    nameTh: 'กระเบื้องปูพื้น',
    slug: 'floor-tiles',
    description: 'Durable, high-load capacity floor tiles designed for contemporary indoor and exterior architectural spaces.',
    descriptionTh: 'กระเบื้องปูพื้นความแข็งแกร่งสูง รองรับน้ำหนักได้ดี สำหรับพื้นที่พักอาศัยและสถาปัตยกรรมระดับไฮเอนด์',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 1,
    isActive: true,
  },
  {
    name: 'Wall Tiles',
    nameTh: 'กระเบื้องบุผนัง',
    slug: 'wall-tiles',
    description: 'Refined decorative wall surfaces featuring sculpted relief textures, satin finishes, and architectural stone patterns.',
    descriptionTh: 'กระเบื้องบุผนังตกแต่งพื้นผิวระดับพรีเมียม เพิ่มมิติและความหรูหราให้พื้นที่สถาปัตยกรรม',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 2,
    isActive: true,
  },
  {
    name: 'Bathroom Tiles',
    nameTh: 'กระเบื้องห้องน้ำ',
    slug: 'bathroom-tiles',
    description: 'Water-resistant, non-slip porcelain tiles crafted for modern luxury spa-inspired bathroom sanctuaries.',
    descriptionTh: 'กระเบื้องห้องน้ำกันลื่น ทนความชื้น ดีไซน์สไตล์สปารีสอร์ทระดับหรู',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 3,
    isActive: true,
  },
  {
    name: 'Outdoor Tiles',
    nameTh: 'กระเบื้องภายนอกและสวน',
    slug: 'outdoor-tiles',
    description: '20mm extra-thick porcelain pavers built for terraces, pool surrounds, and heavy outdoor elements.',
    descriptionTh: 'กระเบื้องภายนอกหนาพิเศษ 20มม. ทนทานต่อแดด ฝน และพื้นที่ลานกิจกรรม',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 4,
    isActive: true,
  },
  {
    name: 'Wood-look Tiles',
    nameTh: 'กระเบื้องลายไม้',
    slug: 'wood-look-tiles',
    description: 'Authentic timber texture with zero maintenance, combining organic warmth with indestructible ceramic performance.',
    descriptionTh: 'กระเบื้องลายไม้ธรรมชาติเสมือนไม้จริง ทนทาน ไม่บวมน้ำ ดูแลรักษาง่าย',
    image: 'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 5,
    isActive: true,
  },
];

export const seedBrands = [
  {
    name: 'SUNMA Atelier',
    slug: 'sunma-atelier',
    description: 'In-house signature collection engineered specifically for luxury private residences.',
    country: 'Thailand / Italy',
    logo: '/images/brands/sunma.png',
    isActive: true,
  },
  {
    name: 'Marmi d\'Italia',
    slug: 'marmi-d-italia',
    description: 'Direct imported Italian extra-large slab porcelain tiles reproducing fine Carrara and Calacatta marble.',
    country: 'Italy',
    logo: '/images/brands/marmi.png',
    isActive: true,
  },
  {
    name: 'Kurokin Surface',
    slug: 'kurokin-surface',
    description: 'Japanese minimal dark stone ceramics featuring tactile micro-textured matte finishes.',
    country: 'Japan',
    logo: '/images/brands/kurokin.png',
    isActive: true,
  },
  {
    name: 'Iberica Ceramica',
    slug: 'iberica-ceramica',
    description: 'Spanish artisan ceramic tiles renowned for warm terracotta and rustic glazed accents.',
    country: 'Spain',
    logo: '/images/brands/iberica.png',
    isActive: true,
  },
];

export const seedCollections = [
  {
    name: 'Calacatta Imperiale Series',
    slug: 'calacatta-imperiale',
    description: 'Timeless white marble veining with subtle warm gold threads.',
    isActive: true,
  },
  {
    name: 'Basaltic Minimal Slab',
    slug: 'basaltic-minimal',
    description: 'Deep stone brown and basalt gray porcelain slabs.',
    isActive: true,
  },
  {
    name: 'Nordic Oak Timber Slat',
    slug: 'nordic-oak',
    description: 'Linear natural oak timber grain tiles.',
    isActive: true,
  },
  {
    name: 'Terrazzo Artisanal',
    slug: 'terrazzo-artisanal',
    description: 'Architectural composite stone with quartz chips.',
    isActive: true,
  },
];

export const seedProducts = [
  {
    productCode: 'SNM-FL-001',
    name: 'Calacatta Oro Polished Slab',
    nameTh: 'กระเบื้องลายหินอ่อน Calacatta Oro ผิวเงา',
    slug: 'calacatta-oro-polished-slab',
    categorySlug: 'floor-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'calacatta-imperiale',
    description: 'High-definition Italian porcelain slab featuring dramatic golden-amber veining over a pristine alabaster background. Perfect for grand living rooms and hotel lobbies.',
    descriptionTh: 'กระเบื้องแผ่นใหญ่ลายหินอ่อน Calacatta Oro นำเข้าจากอิตาลี ลวดลายเส้นทองหรูหรา ผิวเงารัศมีสูง เหมาะสำหรับห้องรับแขกและโถงอาคารพรีเมียม',
    shortDescription: '60x120cm Italian polished porcelain slab with gold veining.',
    shortDescriptionTh: 'กระเบื้องแผ่นใหญ่ 60x120ซม. ผิวเงาลายหินอ่อนขาวทอง',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Polished',
    color: 'White & Gold',
    pattern: 'Marble',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 32.5,
    pricePerPiece: 850,
    pricePerBox: 1700,
    stockPieces: 320,
    featured: true,
    thumbnail: 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-FL-002',
    name: 'Nero Marquina Satin Porcelain',
    nameTh: 'กระเบื้องหินอ่อนสีดำ Nero Marquina ผิวซาติน',
    slug: 'nero-marquina-satin-porcelain',
    categorySlug: 'floor-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'basaltic-minimal',
    description: 'Deep rich charcoal black porcelain with stark white vein contrast. Micro-etched satin surface provides smooth foot feel without glare.',
    descriptionTh: 'กระเบื้องพอร์ซเลนสีดำเข้ม ลายเส้นขาวคมชัด ผิวสัมผัสแบบซาตินเรียบเนียน ไม่สะท้อนแสงจัด เหมาะสำหรับพื้นที่ดีไซน์โมเดิร์นลักชัวรี',
    shortDescription: '60x60cm Satin black marble design tile.',
    shortDescriptionTh: 'กระเบื้อง 60x60ซม. สีดำลายหินอ่อน ผิวสัมผัสซาติน',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Satin',
    color: 'Black',
    pattern: 'Marble',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 30.0,
    pricePerPiece: 420,
    pricePerBox: 1680,
    stockPieces: 450,
    featured: true,
    thumbnail: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-WL-003',
    name: 'Travertino Navona Fluted Wall Tile',
    nameTh: 'กระเบื้องผนัง Travertino Navona ลอนนูน',
    slug: 'travertino-navona-fluted-wall',
    categorySlug: 'wall-tiles',
    brandSlug: 'iberica-ceramica',
    collectionSlug: 'calacatta-imperiale',
    description: '3D linear architectural fluted relief tile replicating ancient Roman travertine. Engineered for feature accent walls in master suites and entry halls.',
    descriptionTh: 'กระเบื้องบุผนังลอน 3 มิติ สไตล์โรมันทราเวอร์ทีน สร้างมิติแสงเงาให้ผนังตกแต่งในห้องนอนและโถงต้อนรับ',
    shortDescription: '30x60cm 3D fluted relief ceramic wall tile.',
    shortDescriptionTh: 'กระเบื้องผนัง 30x60ซม. ลายนูน 3 มิติ หินทราเวอร์ทีน',
    size: '30x60',
    width: 30,
    height: 60,
    thickness: 12,
    material: 'Ceramic',
    surface: 'Carved',
    color: 'Warm Beige',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Spain',
    piecesPerBox: 8,
    coveragePerBox: 1.44,
    weightPerBox: 24.0,
    pricePerPiece: 290,
    pricePerBox: 2320,
    stockPieces: 210,
    featured: true,
    thumbnail: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-WD-004',
    name: 'Nordic Smoked Oak Plank',
    nameTh: 'กระเบื้องลายไม้ Nordic Smoked Oak',
    slug: 'nordic-smoked-oak-plank',
    categorySlug: 'wood-look-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'nordic-oak',
    description: 'Ultra-realistic smoked oak timber plank with deep wood grain embossing and micro-beveled edges. Resistant to scratches, moisture, and high traffic.',
    descriptionTh: 'กระเบื้องพอร์ซเลนลายไม้รมควัน ร่องเสี้ยนไม้ธรรมชาติ สัมผัสเสมือนไม้จริง ทนทาน ไม่ขูดขีด ไม่ขึ้นรา',
    shortDescription: '20x120cm Embossed wood-look porcelain plank.',
    shortDescriptionTh: 'กระเบื้องลายไม้ 20x120ซม. ผิวเสี้ยนไม้ธรรมชาติ',
    size: '20x120',
    width: 20,
    height: 120,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Stone Brown',
    pattern: 'Wood',
    indoorOutdoor: 'Indoor/Outdoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 5,
    coveragePerBox: 1.20,
    weightPerBox: 26.5,
    pricePerPiece: 360,
    pricePerBox: 1800,
    stockPieces: 600,
    featured: true,
    thumbnail: 'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-OD-005',
    name: 'Kurokin Basaltic Paver 20mm',
    nameTh: 'กระเบื้องลานภายนอก Kurokin Basaltic 20มม.',
    slug: 'kurokin-basaltic-paver-20mm',
    categorySlug: 'outdoor-tiles',
    brandSlug: 'kurokin-surface',
    collectionSlug: 'basaltic-minimal',
    description: '20mm heavy-duty structural porcelain paver for outdoor terraces and driveway pavers with R11 slip rating.',
    descriptionTh: 'กระเบื้องปูลานภายนอกหนาพิเศษ 20มม. ค่ากันลื่นระดับ R11 รองรับแรงกดทับสูง และทนต่อสภาพอากาศ',
    shortDescription: '60x60cm 20mm thick R11 outdoor porcelain paver.',
    shortDescriptionTh: 'กระเบื้องปูพื้นภายนอก 60x60ซม. หนา 20มม. กันลื่น R11',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 20,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Dark Gray',
    pattern: 'Concrete',
    indoorOutdoor: 'Outdoor',
    countryOfOrigin: 'Japan',
    piecesPerBox: 2,
    coveragePerBox: 0.72,
    weightPerBox: 33.0,
    pricePerPiece: 680,
    pricePerBox: 1360,
    stockPieces: 180,
    featured: true,
    thumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-BT-006',
    name: 'Pietra di Luna Soft Honed',
    nameTh: 'กระเบื้องห้องน้ำ Pietra di Luna ผิวโฮนซอฟต์',
    slug: 'pietra-di-luna-soft-honed',
    categorySlug: 'bathroom-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'basaltic-minimal',
    description: 'Silky smooth stone-textured tile designed specifically for moisture-prone wet zones and shower enclosures.',
    descriptionTh: 'กระเบื้องผิวสัมผัสโฮนดึงความนุ่มนวลของหินธรรมชาติ ออกแบบมาสำหรับห้องน้ำและโซนเปียกโดยเฉพาะ',
    shortDescription: '60x60cm Soft honed porcelain for moisture zones.',
    shortDescriptionTh: 'กระเบื้องห้องน้ำ 60x60ซม. ผิวซอฟต์โฮน นุ่มเท้า',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Satin',
    color: 'Warm Gray',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 29.0,
    pricePerPiece: 390,
    pricePerBox: 1560,
    stockPieces: 400,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-FL-007',
    name: 'Veneto Terrazzo Micro Charcoal',
    nameTh: 'กระเบื้องเทอร์ราซโซ Veneto Micro Charcoal',
    slug: 'veneto-terrazzo-micro-charcoal',
    categorySlug: 'floor-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'terrazzo-artisanal',
    description: 'Contemporary dark terrazzo featuring fine marble quartz chips embedded in a deep charcoal base matrix.',
    descriptionTh: 'กระเบื้องลายหินขัดเทอร์ราซโซ ชิปควอตซ์ระยิบระยับบนพื้นหลังสีชาโคลสไตล์สถาปัตยกรรมร่วมสมัย',
    shortDescription: '60x60cm Fine dark terrazzo porcelain.',
    shortDescriptionTh: 'กระเบื้องลายหินขัด 60x60ซม. โทนดำชาโคล',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Black',
    pattern: 'Terrazzo',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 31.0,
    pricePerPiece: 450,
    pricePerBox: 1800,
    stockPieces: 290,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-WD-008',
    name: 'Walnut Heritage Chevron Slab',
    nameTh: 'กระเบื้องลายไม้ Walnut Heritage ลายเชฟรอน',
    slug: 'walnut-heritage-chevron-slab',
    categorySlug: 'wood-look-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'nordic-oak',
    description: 'Italian dark walnut grain formatted into chevron geometry for prestigious dining suites and executive lounges.',
    descriptionTh: 'กระเบื้องพอร์ซเลนลายไม้วอลนัทอิตาลี แพทเทิร์นเชฟรอน เพิ่มความภูมิฐานและหรูหราให้ห้องอาหารและเซฟเฮาส์',
    shortDescription: '60x120cm French chevron pattern walnut porcelain slab.',
    shortDescriptionTh: 'กระเบื้องลายไม้ 60x120ซม. แพทเทิร์นเชฟรอนวอลนัท',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Stone Brown',
    pattern: 'Wood',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 32.0,
    pricePerPiece: 920,
    pricePerBox: 1840,
    stockPieces: 150,
    featured: true,
    thumbnail: 'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-WL-009',
    name: 'Zellige Emerald Green Glazed',
    nameTh: 'กระเบื้องเคลือบ Zellige Emerald Green',
    slug: 'zellige-emerald-green-glazed',
    categorySlug: 'wall-tiles',
    brandSlug: 'iberica-ceramica',
    collectionSlug: 'terrazzo-artisanal',
    description: 'Handcrafted-look glossy Moroccan zellige ceramic wall tile in jewel-toned deep emerald green.',
    descriptionTh: 'กระเบื้องตกแต่งสไตล์โมร็อกกัน Zellige ผิวเคลือบเงาสูง เฉดสีเขียวมรกต ลวดลายเฉพาะตัวทรงคุณค่า',
    shortDescription: '30x60cm Moroccan glazed accent wall tile.',
    shortDescriptionTh: 'กระเบื้องตกแต่งผนัง 30x60ซม. สีเขียวมรกตเงาฉ่ำ',
    size: '30x60',
    width: 30,
    height: 60,
    thickness: 9,
    material: 'Ceramic',
    surface: 'Glossy',
    color: 'Emerald Green',
    pattern: 'Terrazzo',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Spain',
    piecesPerBox: 8,
    coveragePerBox: 1.44,
    weightPerBox: 22.0,
    pricePerPiece: 310,
    pricePerBox: 2480,
    stockPieces: 310,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-BT-010',
    name: 'Grigio Carnico Polished Porcelain',
    nameTh: 'กระเบื้องห้องน้ำ Grigio Carnico ลายหินอ่อนเทา',
    slug: 'grigio-carnico-polished-porcelain',
    categorySlug: 'bathroom-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'calacatta-imperiale',
    description: 'Exclusive dark Italian charcoal marble tile with vibrant white veining for sanctuary bathroom walls and floors.',
    descriptionTh: 'กระเบื้องหินอ่อนอิตาลีโทนสีเทาเข้มตัดเส้นขาว ลุคสุขุม ลุ่มลึก มอบบรรยากาศห้องน้ำระดับ 5 ดาว',
    shortDescription: '60x120cm Polished dark gray marble porcelain.',
    shortDescriptionTh: 'กระเบื้อง 60x120ซม. ผิวเงาลายหินอ่อนเทาเข้ม',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Polished',
    color: 'Dark Gray',
    pattern: 'Marble',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 33.0,
    pricePerPiece: 890,
    pricePerBox: 1780,
    stockPieces: 260,
    featured: true,
    thumbnail: 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-OD-011',
    name: 'Sandstone Beige Pool Coping 20mm',
    nameTh: 'กระเบื้องขอบสระ Sandstone Beige 20มม.',
    slug: 'sandstone-beige-pool-coping-20mm',
    categorySlug: 'outdoor-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'basaltic-minimal',
    description: 'Salt-resistant, thermal-shock proof sandstone look porcelain tile designed for swimming pool surrounds.',
    descriptionTh: 'กระเบื้องสระว่ายน้ำและลานกลางแจ้ง ทนคลอรีนและน้ำเค็ม ผิวสัมผัสหินทรายกันลื่น ไม่สะสมความร้อน',
    shortDescription: '60x60cm 20mm Sandstone textured outdoor tile.',
    shortDescriptionTh: 'กระเบื้องลานสระ 60x60ซม. หนา 20มม. กันลื่นสีเบจ',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 20,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Warm Beige',
    pattern: 'Stone',
    indoorOutdoor: 'Outdoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 2,
    coveragePerBox: 0.72,
    weightPerBox: 32.0,
    pricePerPiece: 640,
    pricePerBox: 1280,
    stockPieces: 340,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-FL-012',
    name: 'Concrete Raw Slate Matt',
    nameTh: 'กระเบื้องลายปูนเปลือย Concrete Raw Slate',
    slug: 'concrete-raw-slate-matt',
    categorySlug: 'floor-tiles',
    brandSlug: 'kurokin-surface',
    collectionSlug: 'basaltic-minimal',
    description: 'Architectural industrial micro-cement effect tile with subtle tactile trowel marks.',
    descriptionTh: 'กระเบื้องลายปูนขัดมันสไตล์ลอฟท์ มอบฟีลลิ่งดิบเท่ เรียบหรู สำหรับคอนโดและสตูดิโอสถาปนิก',
    shortDescription: '60x60cm Raw concrete look matt porcelain.',
    shortDescriptionTh: 'กระเบื้องปูนเปลือย 60x60ซม. ผิวด้านสไตล์ลอฟท์',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Warm Gray',
    pattern: 'Concrete',
    indoorOutdoor: 'Indoor/Outdoor',
    countryOfOrigin: 'Japan',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 28.5,
    pricePerPiece: 380,
    pricePerBox: 1520,
    stockPieces: 520,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-WD-013',
    name: 'Teak Natural Heritage Plank',
    nameTh: 'กระเบื้องลายไม้ Teak Natural Heritage',
    slug: 'teak-natural-heritage-plank',
    categorySlug: 'wood-look-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'nordic-oak',
    description: 'Golden Thai teak wood pattern reproduced on durable porcelain tile planks.',
    descriptionTh: 'กระเบื้องลายไม้สักทองธรรมชาติ ลวดลายอบอุ่น ให้ความรู้สึกผ่อนคลายและสัมผัสใกล้ชิดธรรมชาติ',
    shortDescription: '20x120cm Natural teak wood effect plank.',
    shortDescriptionTh: 'กระเบื้องลายไม้สัก 20x120ซม. โทนสีทองธรรมชาติ',
    size: '20x120',
    width: 20,
    height: 120,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Stone Brown',
    pattern: 'Wood',
    indoorOutdoor: 'Indoor/Outdoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 5,
    coveragePerBox: 1.20,
    weightPerBox: 26.0,
    pricePerPiece: 370,
    pricePerBox: 1850,
    stockPieces: 410,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-WL-014',
    name: 'Statuario Micro Velvet Wall',
    nameTh: 'กระเบื้องบุผนัง Statuario Micro Velvet',
    slug: 'statuario-micro-velvet-wall',
    categorySlug: 'wall-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'calacatta-imperiale',
    description: 'Silky micro-velvet finish on white Statuario marble ceramic tiles for luxury vanity backsplash.',
    descriptionTh: 'กระเบื้องผนัง Statuario ขาวบริสุทธิ์ เส้นแร่เทา ผิวสัมผัสแบบไมโครเวลเวท ละมุนดุจกำมะหยี่',
    shortDescription: '30x60cm Statuario velvet finish wall tile.',
    shortDescriptionTh: 'กระเบื้องผนัง 30x60ซม. ผิวเวลเวทสัมผัสนุ่ม',
    size: '30x60',
    width: 30,
    height: 60,
    thickness: 8.5,
    material: 'Ceramic',
    surface: 'Satin',
    color: 'Off-white',
    pattern: 'Marble',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 8,
    coveragePerBox: 1.44,
    weightPerBox: 21.5,
    pricePerPiece: 280,
    pricePerBox: 2240,
    stockPieces: 380,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-FL-015',
    name: 'Volcanic Lava Black Honed',
    nameTh: 'กระเบื้องหินภูเขาไฟ Volcanic Lava Black',
    slug: 'volcanic-lava-black-honed',
    categorySlug: 'floor-tiles',
    brandSlug: 'kurokin-surface',
    collectionSlug: 'basaltic-minimal',
    description: 'Porous volcanic lava stone texture rendered in durable porcelain slabs.',
    descriptionTh: 'กระเบื้องผิวหินภูเขาไฟสีดำเข้ม มอบความเงียบสงบ ลุ่มลึก สไตล์เรียบสัจจะ Zen Architecture',
    shortDescription: '60x120cm Volcanic basalt porcelain slab.',
    shortDescriptionTh: 'กระเบื้องแผ่นใหญ่ 60x120ซม. ผิวหินภูเขาไฟสีดำ',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Black',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor/Outdoor',
    countryOfOrigin: 'Japan',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 34.0,
    pricePerPiece: 790,
    pricePerBox: 1580,
    stockPieces: 230,
    featured: true,
    thumbnail: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-BT-016',
    name: 'Ceppo di Gre Neutral Slab',
    nameTh: 'กระเบื้อง Ceppo di Gre Neutral',
    slug: 'ceppo-di-gre-neutral-slab',
    categorySlug: 'bathroom-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'terrazzo-artisanal',
    description: 'Iconic Milanese Ceppo di Gre pebble aggregate porcelain tile for modern wet-room floors.',
    descriptionTh: 'กระเบื้องหินกรวด Ceppo di Gre สไตล์มิลานยอดนิยม สำหรับพื้นและผนังห้องน้ำสปาสุดหรู',
    shortDescription: '60x60cm Ceppo di Gre stone texture porcelain.',
    shortDescriptionTh: 'กระเบื้องลายหินกรวดมิลาน 60x60ซม.',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Warm Gray',
    pattern: 'Stone',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 4,
    coveragePerBox: 1.44,
    weightPerBox: 30.5,
    pricePerPiece: 490,
    pricePerBox: 1960,
    stockPieces: 330,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-OD-017',
    name: 'Granite Charcoal Paver 20mm',
    nameTh: 'กระเบื้องแกรนิตภายนอก Charcoal 20มม.',
    slug: 'granite-charcoal-paver-20mm',
    categorySlug: 'outdoor-tiles',
    brandSlug: 'kurokin-surface',
    collectionSlug: 'basaltic-minimal',
    description: 'Flame-finished dark granite effect porcelain paver engineered for outdoor driveways and courtyards.',
    descriptionTh: 'กระเบื้องลายแกรนิตพ่นไฟ 20มม. ทนรอยขีดข่วน คราบน้ำมัน และแรงกดทับของรถยนต์',
    shortDescription: '60x60cm 20mm Flamed granite look paver.',
    shortDescriptionTh: 'กระเบื้องลานจอดรถ 60x60ซม. หนา 20มม.',
    size: '60x60',
    width: 60,
    height: 60,
    thickness: 20,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Black',
    pattern: 'Stone',
    indoorOutdoor: 'Outdoor',
    countryOfOrigin: 'Japan',
    piecesPerBox: 2,
    coveragePerBox: 0.72,
    weightPerBox: 33.5,
    pricePerPiece: 710,
    pricePerBox: 1420,
    stockPieces: 190,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-WL-018',
    name: 'Artisan Bronze Metallic Relief',
    nameTh: 'กระเบื้องผนัง Artisan Bronze ลายโลหะ',
    slug: 'artisan-bronze-metallic-relief',
    categorySlug: 'wall-tiles',
    brandSlug: 'iberica-ceramica',
    collectionSlug: 'basaltic-minimal',
    description: 'Subtle metallic shimmering glazed ceramic wall tile designed for high-end bar backdrops and reception desks.',
    descriptionTh: 'กระเบื้องผนังประกายโลหะบรอนซ์ทอง สะท้อนแสงเงาหรูหรา สำหรับผนังเคาน์เตอร์บาร์และแผนกต้อนรับ',
    shortDescription: '30x60cm Shimmering metallic bronze wall tile.',
    shortDescriptionTh: 'กระเบื้องผนัง 30x60ซม. ประกายโลหะบรอนซ์ทอง',
    size: '30x60',
    width: 30,
    height: 60,
    thickness: 9,
    material: 'Ceramic',
    surface: 'Satin',
    color: 'Bronze / Gold',
    pattern: 'Concrete',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Spain',
    piecesPerBox: 8,
    coveragePerBox: 1.44,
    weightPerBox: 23.0,
    pricePerPiece: 340,
    pricePerBox: 2720,
    stockPieces: 270,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-FL-019',
    name: 'Pietra Grey Polished Slab',
    nameTh: 'กระเบื้องลายหินอ่อน Pietra Grey ผิวเงา',
    slug: 'pietra-grey-polished-slab',
    categorySlug: 'floor-tiles',
    brandSlug: 'marmi-d-italia',
    collectionSlug: 'calacatta-imperiale',
    description: 'Persian Pietra grey polished porcelain with charcoal slate tones and fine linear quartz chalk threads.',
    descriptionTh: 'กระเบื้องพอร์ซเลนแผ่นใหญ่ Pietra Grey สีเทาเข้มลายเส้นแร่ขาว ผิวเงาสระกระจก หรูหราเหนือกาลเวลา',
    shortDescription: '60x120cm Polished Pietra Grey marble porcelain.',
    shortDescriptionTh: 'กระเบื้อง 60x120ซม. ลายหินอ่อนสีเทา Pietra Grey',
    size: '60x120',
    width: 60,
    height: 120,
    thickness: 10,
    material: 'Porcelain',
    surface: 'Polished',
    color: 'Dark Gray',
    pattern: 'Marble',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Italy',
    piecesPerBox: 2,
    coveragePerBox: 1.44,
    weightPerBox: 32.8,
    pricePerPiece: 870,
    pricePerBox: 1740,
    stockPieces: 240,
    featured: true,
    thumbnail: 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    productCode: 'SNM-WD-020',
    name: 'Ebony Black Wood Plank',
    nameTh: 'กระเบื้องลายไม้ไม้มะเกลือ Ebony Black',
    slug: 'ebony-black-wood-plank',
    categorySlug: 'wood-look-tiles',
    brandSlug: 'sunma-atelier',
    collectionSlug: 'nordic-oak',
    description: 'Jet black stained wood-look porcelain planks for sophisticated dark moody interiors and architectural suites.',
    descriptionTh: 'กระเบื้องลายไม้สีดำไม้มะเกลือ ดึงสายตาด้วยความลุ่มลึก เพิ่มเอกลักษณ์ให้พื้นที่ส่วนตัว',
    shortDescription: '20x120cm Black stained timber look porcelain plank.',
    shortDescriptionTh: 'กระเบื้องลายไม้สีดำ 20x120ซม.',
    size: '20x120',
    width: 20,
    height: 120,
    thickness: 9.5,
    material: 'Porcelain',
    surface: 'Matt',
    color: 'Black',
    pattern: 'Wood',
    indoorOutdoor: 'Indoor',
    countryOfOrigin: 'Thailand',
    piecesPerBox: 5,
    coveragePerBox: 1.20,
    weightPerBox: 26.2,
    pricePerPiece: 390,
    pricePerBox: 1950,
    stockPieces: 300,
    featured: false,
    thumbnail: 'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
    ],
  },
];

export const seedRooms = [
  {
    name: 'Modern Architectural Living Room',
    nameTh: 'ห้องรับแขกสถาปัตยกรรมร่วมสมัย',
    slug: 'living-room',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80',
    description: 'Spacious high-ceiling lounge with floor-to-ceiling glass and panoramic garden view.',
    areas: [
      {
        name: 'Main Floor Area',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,520 1400,520 1400,900 0,900',
        defaultTileAspectRatio: '1:1',
      },
    ],
  },
  {
    name: 'Luxury Sanctuary Bathroom',
    nameTh: 'ห้องน้ำดีไซน์รีสอร์ทระดับหรู',
    slug: 'bathroom',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1400&q=80',
    description: 'Minimal spa bathroom with freestanding tub and floating quartz vanity.',
    areas: [
      {
        name: 'Bathroom Floor',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,620 1400,620 1400,900 0,900',
        defaultTileAspectRatio: '1:1',
      },
      {
        name: 'Vanity & Shower Feature Wall',
        areaType: 'Wall' as const,
        maskSvgPolygon: '150,100 1250,100 1250,620 150,620',
        defaultTileAspectRatio: '1:2',
      },
    ],
  },
  {
    name: 'Master Architectural Bedroom',
    nameTh: 'ห้องนอนมาสเตอร์สวีท',
    slug: 'bedroom',
    imageUrl: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1400&q=80',
    description: 'Serene master bedroom suite with warm lighting and ambient acoustic finishes.',
    areas: [
      {
        name: 'Bedroom Suite Floor',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,580 1400,580 1400,900 0,900',
        defaultTileAspectRatio: '1:1',
      },
    ],
  },
  {
    name: 'Chef Kitchen & Dining Space',
    nameTh: 'ห้องครัวและโซนรับประทานอาหาร',
    slug: 'kitchen',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1400&q=80',
    description: 'Professional chef kitchen with dark marble waterfall island and brass fixtures.',
    areas: [
      {
        name: 'Kitchen & Island Floor',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,650 1400,650 1400,900 0,900',
        defaultTileAspectRatio: '1:2',
      },
      {
        name: 'Kitchen Backsplash Wall',
        areaType: 'Backsplash' as const,
        maskSvgPolygon: '200,300 1200,300 1200,480 200,480',
        defaultTileAspectRatio: '1:2',
      },
    ],
  },
  {
    name: 'Outdoor Terrace & Pool Deck',
    nameTh: 'ลานระเบียงและสระว่ายน้ำภายนอก',
    slug: 'outdoor',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1400&q=80',
    description: 'Sunlit alfresco dining terrace overlooking infinity swimming pool.',
    areas: [
      {
        name: 'Terrace Floor Paver',
        areaType: 'Floor' as const,
        maskSvgPolygon: '0,500 1400,500 1400,900 0,900',
        defaultTileAspectRatio: '1:1',
      },
    ],
  },
];

export const seedPromotions = [
  {
    name: 'Grand Architectural Launch - 15% OFF Italian Slabs',
    discountPercentage: '15.00',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    isActive: true,
    minQuantity: 2,
  },
];
