import { Product, Category, Brand, Collection, Order, Cart, Promotion, Room, UserProfile } from '../types';

class StoreRepository {
  public categories: Category[] = [
    {
      id: 'cat-1',
      name: 'Floor Tiles',
      nameTh: 'กระเบื้องปูพื้น',
      slug: 'floor-tiles',
      description: 'Durable, high-load capacity floor tiles designed for contemporary indoor and exterior architectural spaces.',
      descriptionTh: 'กระเบื้องปูพื้นความแข็งแกร่งสูง รองรับน้ำหนักได้ดี สำหรับพื้นที่พักอาศัยและสถาปัตยกรรมระดับไฮเอนด์',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      sortOrder: 1,
      isActive: true,
    },
    {
      id: 'cat-2',
      name: 'Wall Tiles',
      nameTh: 'กระเบื้องบุผนัง',
      slug: 'wall-tiles',
      description: 'Refined decorative wall surfaces featuring sculpted relief textures, satin finishes, and architectural stone patterns.',
      descriptionTh: 'กระเบื้องบุผนังตกแต่งพื้นผิวระดับพรีเมียม เพิ่มมิติและความหรูหราให้พื้นที่สถาปัตยกรรม',
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      sortOrder: 2,
      isActive: true,
    },
    {
      id: 'cat-3',
      name: 'Bathroom Tiles',
      nameTh: 'กระเบื้องห้องน้ำ',
      slug: 'bathroom-tiles',
      description: 'Water-resistant, non-slip porcelain tiles crafted for modern luxury spa-inspired bathroom sanctuaries.',
      descriptionTh: 'กระเบื้องห้องน้ำกันลื่น ทนความชื้น ดีไซน์สไตล์สปารีสอร์ทระดับหรู',
      image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
      sortOrder: 3,
      isActive: true,
    },
    {
      id: 'cat-4',
      name: 'Outdoor Tiles',
      nameTh: 'กระเบื้องภายนอกและสวน',
      slug: 'outdoor-tiles',
      description: '20mm extra-thick porcelain pavers built for terraces, pool surrounds, and heavy outdoor elements.',
      descriptionTh: 'กระเบื้องภายนอกหนาพิเศษ 20มม. ทนทานต่อแดด ฝน และพื้นที่ลานกิจกรรม',
      image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
      sortOrder: 4,
      isActive: true,
    },
    {
      id: 'cat-5',
      name: 'Wood-look Tiles',
      nameTh: 'กระเบื้องลายไม้',
      slug: 'wood-look-tiles',
      description: 'Authentic timber texture with zero maintenance, combining organic warmth with indestructible ceramic performance.',
      descriptionTh: 'กระเบื้องลายไม้ธรรมชาติเสมือนไม้จริง ทนทาน ไม่บวมน้ำ ดูแลรักษาง่าย',
      image: 'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1200&q=80',
      sortOrder: 5,
      isActive: true,
    },
  ];

  public brands: Brand[] = [
    {
      id: 'brand-1',
      name: 'SUNMA Atelier',
      slug: 'sunma-atelier',
      description: 'In-house signature collection engineered specifically for luxury private residences.',
      country: 'Thailand / Italy',
      logo: 'SUNMA Atelier',
      isActive: true,
    },
    {
      id: 'brand-2',
      name: 'Marmi d\'Italia',
      slug: 'marmi-d-italia',
      description: 'Direct imported Italian extra-large slab porcelain tiles reproducing fine Carrara and Calacatta marble.',
      country: 'Italy',
      logo: 'Marmi d\'Italia',
      isActive: true,
    },
    {
      id: 'brand-3',
      name: 'Kurokin Surface',
      slug: 'kurokin-surface',
      description: 'Japanese minimal dark stone ceramics featuring tactile micro-textured matte finishes.',
      country: 'Japan',
      logo: 'Kurokin Surface',
      isActive: true,
    },
    {
      id: 'brand-4',
      name: 'Iberica Ceramica',
      slug: 'iberica-ceramica',
      description: 'Spanish artisan ceramic tiles renowned for warm terracotta and rustic glazed accents.',
      country: 'Spain',
      logo: 'Iberica Ceramica',
      isActive: true,
    },
  ];

  public collections: Collection[] = [
    {
      id: 'coll-1',
      name: 'Calacatta Imperiale Series',
      slug: 'calacatta-imperiale',
      description: 'Timeless white marble veining with subtle warm gold threads.',
      isActive: true,
    },
    {
      id: 'coll-2',
      name: 'Basaltic Minimal Slab',
      slug: 'basaltic-minimal',
      description: 'Deep stone brown and basalt gray porcelain slabs.',
      isActive: true,
    },
    {
      id: 'coll-3',
      name: 'Nordic Oak Timber Slat',
      slug: 'nordic-oak',
      description: 'Linear natural oak timber grain tiles.',
      isActive: true,
    },
  ];

  public products: Product[] = [
    {
      id: 'prod-1',
      productCode: 'SNM-FL-001',
      name: 'Calacatta Oro Polished Slab',
      nameTh: 'กระเบื้องลายหินอ่อน Calacatta Oro ผิวเงา',
      slug: 'calacatta-oro-polished-slab',
      categoryId: 'cat-1',
      categoryName: 'Floor Tiles',
      brandId: 'brand-2',
      brandName: 'Marmi d\'Italia',
      collectionId: 'coll-1',
      collectionName: 'Calacatta Imperiale Series',
      description: 'High-definition Italian porcelain slab featuring dramatic golden-amber veining over a pristine alabaster background. Perfect for grand living rooms and hotel lobbies.',
      descriptionTh: 'กระเบื้องแผ่นใหญ่ลายหินอ่อน Calacatta Oro นำเข้าจากอิตาลี ลวดลายเส้นทองหรูหรา ผิวเงารัศมีสูง เหมาะสำหรับห้องรับแขกและโถงอาคารพรีเมียม',
      shortDescription: '60x120cm Italian polished porcelain slab with gold veining.',
      shortDescriptionTh: 'กระเบื้องแผ่นใหญ่ 60x120ซม. ผิวเงาลายหินอ่อนขาวทอง',
      size: '60x120',
      width: 60,
      height: 120,
      thickness: 10,
      material: 'Porcelain',
      surface: 'Polished',
      color: 'White & Gold',
      pattern: 'Marble',
      indoorOutdoor: 'Indoor',
      countryOfOrigin: 'Italy',
      piecesPerBox: 2,
      coveragePerBox: 1.44,
      weightPerBox: 32.5,
      pricePerPiece: 850,
      pricePerBox: 1700,
      stockPieces: 320,
      minimumOrderQuantity: 1,
      status: 'PUBLISHED',
      featured: true,
      thumbnail: 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
      images: [
        'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
      ],
      createdAt: '2026-01-10T08:00:00Z',
      updatedAt: '2026-01-10T08:00:00Z',
    },
    {
      id: 'prod-2',
      productCode: 'SNM-FL-002',
      name: 'Nero Marquina Satin Porcelain',
      nameTh: 'กระเบื้องหินอ่อนสีดำ Nero Marquina ผิวซาติน',
      slug: 'nero-marquina-satin-porcelain',
      categoryId: 'cat-1',
      categoryName: 'Floor Tiles',
      brandId: 'brand-1',
      brandName: 'SUNMA Atelier',
      collectionId: 'coll-2',
      collectionName: 'Basaltic Minimal Slab',
      description: 'Deep rich charcoal black porcelain with stark white vein contrast. Micro-etched satin surface provides smooth foot feel without glare.',
      descriptionTh: 'กระเบื้องพอร์ซเลนสีดำเข้ม ลายเส้นขาวคมชัด ผิวสัมผัสแบบซาตินเรียบเนียน ไม่สะท้อนแสงจัด เหมาะสำหรับพื้นที่ดีไซน์โมเดิร์นลักชัวรี',
      shortDescription: '60x60cm Satin black marble design tile.',
      shortDescriptionTh: 'กระเบื้อง 60x60ซม. สีดำลายหินอ่อน ผิวสัมผัสซาติน',
      size: '60x60',
      width: 60,
      height: 60,
      thickness: 9.5,
      material: 'Porcelain',
      surface: 'Satin',
      color: 'Black',
      pattern: 'Marble',
      indoorOutdoor: 'Indoor',
      countryOfOrigin: 'Thailand',
      piecesPerBox: 4,
      coveragePerBox: 1.44,
      weightPerBox: 30.0,
      pricePerPiece: 420,
      pricePerBox: 1680,
      stockPieces: 450,
      minimumOrderQuantity: 1,
      status: 'PUBLISHED',
      featured: true,
      thumbnail: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
      images: [
        'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
      ],
      createdAt: '2026-01-12T09:30:00Z',
      updatedAt: '2026-01-12T09:30:00Z',
    },
    {
      id: 'prod-3',
      productCode: 'SNM-WL-003',
      name: 'Travertino Navona Fluted Wall Tile',
      nameTh: 'กระเบื้องผนัง Travertino Navona ลอนนูน',
      slug: 'travertino-navona-fluted-wall',
      categoryId: 'cat-2',
      categoryName: 'Wall Tiles',
      brandId: 'brand-4',
      brandName: 'Iberica Ceramica',
      collectionId: 'coll-1',
      collectionName: 'Calacatta Imperiale Series',
      description: '3D linear architectural fluted relief tile replicating ancient Roman travertine. Engineered for feature accent walls in master suites and entry halls.',
      descriptionTh: 'กระเบื้องบุผนังลอน 3 มิติ สไตล์โรมันทราเวอร์ทีน สร้างมิติแสงเงาให้ผนังตกแต่งในห้องนอนและโถงต้อนรับ',
      shortDescription: '30x60cm 3D fluted relief ceramic wall tile.',
      shortDescriptionTh: 'กระเบื้องผนัง 30x60ซม. ลายนูน 3 มิติ หินทราเวอร์ทีน',
      size: '30x60',
      width: 30,
      height: 60,
      thickness: 12,
      material: 'Ceramic',
      surface: 'Carved',
      color: 'Warm Beige',
      pattern: 'Stone',
      indoorOutdoor: 'Indoor',
      countryOfOrigin: 'Spain',
      piecesPerBox: 8,
      coveragePerBox: 1.44,
      weightPerBox: 24.0,
      pricePerPiece: 290,
      pricePerBox: 2320,
      stockPieces: 210,
      minimumOrderQuantity: 1,
      status: 'PUBLISHED',
      featured: true,
      thumbnail: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80',
      images: [
        'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80',
      ],
      createdAt: '2026-01-14T11:00:00Z',
      updatedAt: '2026-01-14T11:00:00Z',
    },
    {
      id: 'prod-4',
      productCode: 'SNM-WD-004',
      name: 'Nordic Smoked Oak Plank',
      nameTh: 'กระเบื้องลายไม้ Nordic Smoked Oak',
      slug: 'nordic-smoked-oak-plank',
      categoryId: 'cat-5',
      categoryName: 'Wood-look Tiles',
      brandId: 'brand-1',
      brandName: 'SUNMA Atelier',
      collectionId: 'coll-3',
      collectionName: 'Nordic Oak Timber Slat',
      description: 'Ultra-realistic smoked oak timber plank with deep wood grain embossing and micro-beveled edges. Resistant to scratches, moisture, and high traffic.',
      descriptionTh: 'กระเบื้องพอร์ซเลนลายไม้รมควัน ร่องเสี้ยนไม้ธรรมชาติ สัมผัสเสมือนไม้จริง ทนทาน ไม่ขูดขีด ไม่ขึ้นรา',
      shortDescription: '20x120cm Embossed wood-look porcelain plank.',
      shortDescriptionTh: 'กระเบื้องลายไม้ 20x120ซม. ผิวเสี้ยนไม้ธรรมชาติ',
      size: '20x120',
      width: 20,
      height: 120,
      thickness: 9.5,
      material: 'Porcelain',
      surface: 'Matt',
      color: 'Stone Brown',
      pattern: 'Wood',
      indoorOutdoor: 'Indoor/Outdoor',
      countryOfOrigin: 'Thailand',
      piecesPerBox: 5,
      coveragePerBox: 1.20,
      weightPerBox: 26.5,
      pricePerPiece: 360,
      pricePerBox: 1800,
      stockPieces: 600,
      minimumOrderQuantity: 1,
      status: 'PUBLISHED',
      featured: true,
      thumbnail: 'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
      images: [
        'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
      ],
      createdAt: '2026-01-16T14:15:00Z',
      updatedAt: '2026-01-16T14:15:00Z',
    },
    {
      id: 'prod-5',
      productCode: 'SNM-OD-005',
      name: 'Kurokin Basaltic Paver 20mm',
      nameTh: 'กระเบื้องลานภายนอก Kurokin Basaltic 20มม.',
      slug: 'kurokin-basaltic-paver-20mm',
      categoryId: 'cat-4',
      categoryName: 'Outdoor Tiles',
      brandId: 'brand-3',
      brandName: 'Kurokin Surface',
      collectionId: 'coll-2',
      collectionName: 'Basaltic Minimal Slab',
      description: '20mm heavy-duty structural porcelain paver for outdoor terraces and driveway pavers with R11 slip rating.',
      descriptionTh: 'กระเบื้องปูลานภายนอกหนาพิเศษ 20มม. ค่ากันลื่นระดับ R11 รองรับแรงกดทับสูง และทนต่อสภาพอากาศ',
      shortDescription: '60x60cm 20mm thick R11 outdoor porcelain paver.',
      shortDescriptionTh: 'กระเบื้องปูพื้นภายนอก 60x60ซม. หนา 20มม. กันลื่น R11',
      size: '60x60',
      width: 60,
      height: 60,
      thickness: 20,
      material: 'Porcelain',
      surface: 'Matt',
      color: 'Dark Gray',
      pattern: 'Concrete',
      indoorOutdoor: 'Outdoor',
      countryOfOrigin: 'Japan',
      piecesPerBox: 2,
      coveragePerBox: 0.72,
      weightPerBox: 33.0,
      pricePerPiece: 680,
      pricePerBox: 1360,
      stockPieces: 180,
      minimumOrderQuantity: 1,
      status: 'PUBLISHED',
      featured: true,
      thumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
      images: [
        'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
      ],
      createdAt: '2026-01-18T16:40:00Z',
      updatedAt: '2026-01-18T16:40:00Z',
    },
    {
      id: 'prod-6',
      productCode: 'SNM-BT-006',
      name: 'Pietra di Luna Soft Honed',
      nameTh: 'กระเบื้องห้องน้ำ Pietra di Luna ผิวโฮนซอฟต์',
      slug: 'pietra-di-luna-soft-honed',
      categoryId: 'cat-3',
      categoryName: 'Bathroom Tiles',
      brandId: 'brand-1',
      brandName: 'SUNMA Atelier',
      collectionId: 'coll-2',
      collectionName: 'Basaltic Minimal Slab',
      description: 'Silky smooth stone-textured tile designed specifically for moisture-prone wet zones and shower enclosures.',
      descriptionTh: 'กระเบื้องผิวสัมผัสโฮนดึงความนุ่มนวลของหินธรรมชาติ ออกแบบมาสำหรับห้องน้ำและโซนเปียกโดยเฉพาะ',
      shortDescription: '60x60cm Soft honed porcelain for moisture zones.',
      shortDescriptionTh: 'กระเบื้องห้องน้ำ 60x60ซม. ผิวซอฟต์โฮน นุ่มเท้า',
      size: '60x60',
      width: 60,
      height: 60,
      thickness: 9.5,
      material: 'Porcelain',
      surface: 'Satin',
      color: 'Warm Gray',
      pattern: 'Stone',
      indoorOutdoor: 'Indoor',
      countryOfOrigin: 'Thailand',
      piecesPerBox: 4,
      coveragePerBox: 1.44,
      weightPerBox: 29.0,
      pricePerPiece: 390,
      pricePerBox: 1560,
      stockPieces: 400,
      minimumOrderQuantity: 1,
      status: 'PUBLISHED',
      featured: false,
      thumbnail: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80',
      images: [
        'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80',
      ],
      createdAt: '2026-01-20T10:00:00Z',
      updatedAt: '2026-01-20T10:00:00Z',
    },
    {
      id: 'prod-7',
      productCode: 'SNM-FL-007',
      name: 'Veneto Terrazzo Micro Charcoal',
      nameTh: 'กระเบื้องเทอร์ราซโซ Veneto Micro Charcoal',
      slug: 'veneto-terrazzo-micro-charcoal',
      categoryId: 'cat-1',
      categoryName: 'Floor Tiles',
      brandId: 'brand-1',
      brandName: 'SUNMA Atelier',
      description: 'Contemporary dark terrazzo featuring fine marble quartz chips embedded in a deep charcoal base matrix.',
      descriptionTh: 'กระเบื้องลายหินขัดเทอร์ราซโซ ชิปควอตซ์ระยิบระยับบนพื้นหลังสีชาโคลสไตล์สถาปัตยกรรมร่วมสมัย',
      shortDescription: '60x60cm Fine dark terrazzo porcelain.',
      shortDescriptionTh: 'กระเบื้องลายหินขัด 60x60ซม. โทนดำชาโคล',
      size: '60x60',
      width: 60,
      height: 60,
      thickness: 10,
      material: 'Porcelain',
      surface: 'Matt',
      color: 'Black',
      pattern: 'Terrazzo',
      indoorOutdoor: 'Indoor',
      countryOfOrigin: 'Thailand',
      piecesPerBox: 4,
      coveragePerBox: 1.44,
      weightPerBox: 31.0,
      pricePerPiece: 450,
      pricePerBox: 1800,
      stockPieces: 290,
      minimumOrderQuantity: 1,
      status: 'PUBLISHED',
      featured: false,
      thumbnail: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1000&q=80',
      images: [
        'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1000&q=80',
      ],
      createdAt: '2026-01-22T08:00:00Z',
      updatedAt: '2026-01-22T08:00:00Z',
    },
    {
      id: 'prod-8',
      productCode: 'SNM-WD-008',
      name: 'Walnut Heritage Chevron Slab',
      nameTh: 'กระเบื้องลายไม้ Walnut Heritage ลายเชฟรอน',
      slug: 'walnut-heritage-chevron-slab',
      categoryId: 'cat-5',
      categoryName: 'Wood-look Tiles',
      brandId: 'brand-2',
      brandName: 'Marmi d\'Italia',
      collectionId: 'coll-3',
      collectionName: 'Nordic Oak Timber Slat',
      description: 'Italian dark walnut grain formatted into chevron geometry for prestigious dining suites and executive lounges.',
      descriptionTh: 'กระเบื้องพอร์ซเลนลายไม้วอลนัทอิตาลี แพทเทิร์นเชฟรอน เพิ่มความภูมิฐานและหรูหราให้ห้องอาหารและเซฟเฮาส์',
      shortDescription: '60x120cm French chevron pattern walnut porcelain slab.',
      shortDescriptionTh: 'กระเบื้องลายไม้ 60x120ซม. แพทเทิร์นเชฟรอนวอลนัท',
      size: '60x120',
      width: 60,
      height: 120,
      thickness: 10,
      material: 'Porcelain',
      surface: 'Matt',
      color: 'Stone Brown',
      pattern: 'Wood',
      indoorOutdoor: 'Indoor',
      countryOfOrigin: 'Italy',
      piecesPerBox: 2,
      coveragePerBox: 1.44,
      weightPerBox: 32.0,
      pricePerPiece: 920,
      pricePerBox: 1840,
      stockPieces: 150,
      minimumOrderQuantity: 1,
      status: 'PUBLISHED',
      featured: true,
      thumbnail: 'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
      images: [
        'https://images.unsplash.com/photo-1513161455074-7554c9146233?auto=format&fit=crop&w=1000&q=80',
      ],
      createdAt: '2026-01-24T12:00:00Z',
      updatedAt: '2026-01-24T12:00:00Z',
    },
    {
      id: 'prod-9',
      productCode: 'SNM-WL-009',
      name: 'Zellige Emerald Green Glazed',
      nameTh: 'กระเบื้องเคลือบ Zellige Emerald Green',
      slug: 'zellige-emerald-green-glazed',
      categoryId: 'cat-2',
      categoryName: 'Wall Tiles',
      brandId: 'brand-4',
      brandName: 'Iberica Ceramica',
      description: 'Handcrafted-look glossy Moroccan zellige ceramic wall tile in jewel-toned deep emerald green.',
      descriptionTh: 'กระเบื้องตกแต่งสไตล์โมร็อกกัน Zellige ผิวเคลือบเงาสูง เฉดสีเขียวมรกต ลวดลายเฉพาะตัวทรงคุณค่า',
      shortDescription: '30x60cm Moroccan glazed accent wall tile.',
      shortDescriptionTh: 'กระเบื้องตกแต่งผนัง 30x60ซม. สีเขียวมรกตเงาฉ่ำ',
      size: '30x60',
      width: 30,
      height: 60,
      thickness: 9,
      material: 'Ceramic',
      surface: 'Glossy',
      color: 'Emerald Green',
      pattern: 'Terrazzo',
      indoorOutdoor: 'Indoor',
      countryOfOrigin: 'Spain',
      piecesPerBox: 8,
      coveragePerBox: 1.44,
      weightPerBox: 22.0,
      pricePerPiece: 310,
      pricePerBox: 2480,
      stockPieces: 310,
      minimumOrderQuantity: 1,
      status: 'PUBLISHED',
      featured: false,
      thumbnail: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1000&q=80',
      images: [
        'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1000&q=80',
      ],
      createdAt: '2026-01-26T09:00:00Z',
      updatedAt: '2026-01-26T09:00:00Z',
    },
    {
      id: 'prod-10',
      productCode: 'SNM-BT-010',
      name: 'Grigio Carnico Polished Porcelain',
      nameTh: 'กระเบื้องห้องน้ำ Grigio Carnico ลายหินอ่อนเทา',
      slug: 'grigio-carnico-polished-porcelain',
      categoryId: 'cat-3',
      categoryName: 'Bathroom Tiles',
      brandId: 'brand-2',
      brandName: 'Marmi d\'Italia',
      collectionId: 'coll-1',
      collectionName: 'Calacatta Imperiale Series',
      description: 'Exclusive dark Italian charcoal marble tile with vibrant white veining for sanctuary bathroom walls and floors.',
      descriptionTh: 'กระเบื้องหินอ่อนอิตาลีโทนสีเทาเข้มตัดเส้นขาว ลุคสุขุม ลุ่มลึก มอบบรรยากาศห้องน้ำระดับ 5 ดาว',
      shortDescription: '60x120cm Polished dark gray marble porcelain.',
      shortDescriptionTh: 'กระเบื้อง 60x120ซม. ผิวเงาลายหินอ่อนเทาเข้ม',
      size: '60x120',
      width: 60,
      height: 120,
      thickness: 10,
      material: 'Porcelain',
      surface: 'Polished',
      color: 'Dark Gray',
      pattern: 'Marble',
      indoorOutdoor: 'Indoor',
      countryOfOrigin: 'Italy',
      piecesPerBox: 2,
      coveragePerBox: 1.44,
      weightPerBox: 33.0,
      pricePerPiece: 890,
      pricePerBox: 1780,
      stockPieces: 260,
      minimumOrderQuantity: 1,
      status: 'PUBLISHED',
      featured: true,
      thumbnail: 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
      images: [
        'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
      ],
      createdAt: '2026-01-28T14:00:00Z',
      updatedAt: '2026-01-28T14:00:00Z',
    },
  ];

  public carts: Map<string, Cart> = new Map();
  public wishlists: Map<string, string[]> = new Map(); // userId -> array of productIds
  public orders: Order[] = [
    {
      id: 'ord-1001',
      orderNumber: 'SNM-202608-001',
      userId: 'user-architect',
      userEmail: 'architect@studio-lux.com',
      status: 'Confirmed',
      totalAmount: 18520,
      shippingFee: 500,
      taxAmount: 1210,
      paymentMethod: 'Bank Transfer',
      shippingAddress: {
        recipientName: 'Somchai Studio Lux',
        phone: '0812345678',
        addressLine: '88/12 Sukhumvit 55 Road',
        subdistrict: 'Klongtan Nua',
        district: 'Vadhana',
        province: 'Bangkok',
        postalCode: '10110',
      },
      recipientName: 'Somchai Studio Lux',
      recipientPhone: '0812345678',
      taxInvoiceRequested: true,
      taxInvoiceDetails: {
        companyName: 'Studio Lux Architecture Co., Ltd.',
        taxId: '0105565012345',
        branch: 'Head Office',
        address: '88/12 Sukhumvit 55 Road, Klongtan Nua, Vadhana, Bangkok 10110',
      },
      items: [
        {
          id: 'item-1',
          productId: 'prod-1',
          productName: 'Calacatta Oro Polished Slab',
          productCode: 'SNM-FL-001',
          variantInfo: '60x120cm',
          quantity: 20, // 20 pieces = 10 boxes
          pricePerUnit: 850,
          totalPrice: 17000,
          thumbnail: 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1000&q=80',
        },
      ],
      createdAt: '2026-08-25T11:20:00Z',
      updatedAt: '2026-08-25T11:30:00Z',
    },
  ];

  public promotions: Promotion[] = [
    {
      id: 'promo-1',
      name: 'Grand Architectural Launch - 15% OFF Italian Slabs',
      discountPercentage: 15,
      startDate: '2026-01-01',
      endDate: '2026-12-31',
      isActive: true,
      minQuantity: 2,
      categoryIds: ['cat-1'],
    },
  ];

  public rooms: Room[] = [
    {
      id: 'room-1',
      name: 'Modern Architectural Living Room',
      nameTh: 'ห้องรับแขกสถาปัตยกรรมร่วมสมัย',
      slug: 'living-room',
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80',
      description: 'Spacious high-ceiling lounge with floor-to-ceiling glass and panoramic garden view.',
      areas: [
        {
          id: 'area-1-1',
          roomId: 'room-1',
          name: 'Main Living Room Floor',
          areaType: 'Floor',
          maskSvgPolygon: '0,520 1400,520 1400,900 0,900',
          defaultTileAspectRatio: '1:1',
        },
      ],
    },
    {
      id: 'room-2',
      name: 'Luxury Sanctuary Bathroom',
      nameTh: 'ห้องน้ำดีไซน์รีสอร์ทระดับหรู',
      slug: 'bathroom',
      imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1400&q=80',
      description: 'Minimal spa bathroom with freestanding tub and floating quartz vanity.',
      areas: [
        {
          id: 'area-2-1',
          roomId: 'room-2',
          name: 'Bathroom Floor',
          areaType: 'Floor',
          maskSvgPolygon: '0,620 1400,620 1400,900 0,900',
          defaultTileAspectRatio: '1:1',
        },
        {
          id: 'area-2-2',
          roomId: 'room-2',
          name: 'Vanity & Shower Feature Wall',
          areaType: 'Wall',
          maskSvgPolygon: '150,100 1250,100 1250,620 150,620',
          defaultTileAspectRatio: '1:2',
        },
      ],
    },
    {
      id: 'room-3',
      name: 'Master Architectural Bedroom',
      nameTh: 'ห้องนอนมาสเตอร์สวีท',
      slug: 'bedroom',
      imageUrl: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1400&q=80',
      description: 'Serene master bedroom suite with warm lighting and ambient acoustic finishes.',
      areas: [
        {
          id: 'area-3-1',
          roomId: 'room-3',
          name: 'Bedroom Suite Floor',
          areaType: 'Floor',
          maskSvgPolygon: '0,580 1400,580 1400,900 0,900',
          defaultTileAspectRatio: '1:1',
        },
      ],
    },
    {
      id: 'room-4',
      name: 'Chef Kitchen & Dining Space',
      nameTh: 'ห้องครัวและโซนรับประทานอาหาร',
      slug: 'kitchen',
      imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1400&q=80',
      description: 'Professional chef kitchen with dark marble waterfall island and brass fixtures.',
      areas: [
        {
          id: 'area-4-1',
          roomId: 'room-4',
          name: 'Kitchen & Island Floor',
          areaType: 'Floor',
          maskSvgPolygon: '0,650 1400,650 1400,900 0,900',
          defaultTileAspectRatio: '1:2',
        },
        {
          id: 'area-4-2',
          roomId: 'room-4',
          name: 'Kitchen Backsplash Wall',
          areaType: 'Backsplash',
          maskSvgPolygon: '200,300 1200,300 1200,480 200,480',
          defaultTileAspectRatio: '1:2',
        },
      ],
    },
    {
      id: 'room-5',
      name: 'Outdoor Terrace & Pool Deck',
      nameTh: 'ลานระเบียงและสระว่ายน้ำภายนอก',
      slug: 'outdoor',
      imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1400&q=80',
      description: 'Sunlit alfresco dining terrace overlooking infinity swimming pool.',
      areas: [
        {
          id: 'area-5-1',
          roomId: 'room-5',
          name: 'Terrace Floor Paver',
          areaType: 'Floor',
          maskSvgPolygon: '0,500 1400,500 1400,900 0,900',
          defaultTileAspectRatio: '1:1',
        },
      ],
    },
  ];

  public users: UserProfile[] = [
    {
      id: 'user-admin',
      email: 'admin@sunmaceramic.com',
      fullName: 'SUNMA Senior Administrator',
      phone: '+66 2 800 9999',
      role: 'ADMIN',
      createdAt: '2026-01-01T00:00:00Z',
    },
    {
      id: 'user-architect',
      email: 'architect@studio-lux.com',
      fullName: 'Somchai Studio Lux',
      phone: '+66 81 234 5678',
      role: 'USER',
      createdAt: '2026-01-15T00:00:00Z',
    },
  ];
}

export const store = new StoreRepository();
